# Getting Started with dscompanion

The fastest path to a working `dscompanion` pipeline: install, fetch a real dataset,
run the smallest config that works, and look at what came back. No deep explanation
here — that's what [`02_classification_bank_marketing.ipynb`](02_classification_bank_marketing.ipynb)
is for. See [`README.md`](README.md) for the full notebook index.

In [1]:
!pip install -q dscompanion[notebooks]

zsh:1: no matches found: dscompanion[notebooks]

## The dataset

We'll use the UCI **Bank Marketing** dataset — records from a Portuguese bank's phone
marketing campaign for term deposits. The target column is `y`: did the client
subscribe (`"yes"`/`"no"`)? That makes this a binary classification problem.

dscompanion's classification models expect a **numeric** target (`0`/`1`), not a
categorical string label — so we map `"yes"`/`"no"` to `1`/`0` before saving.

In [2]:
from pathlib import Path
from ucimlrepo import fetch_ucirepo

cache_dir = Path(".data_cache")
cache_dir.mkdir(exist_ok=True)
data_path = cache_dir / "bank_marketing.parquet"

if not data_path.exists():
    ds = fetch_ucirepo(id=222)
    df = ds.data.features.copy()
    df["y"] = ds.data.targets["y"].map({"yes": 1, "no": 0})
    df.to_parquet(data_path, index=False)
else:
    import pandas as pd
    df = pd.read_parquet(data_path)

print(f"Saved {data_path} — {df.shape[0]} rows, {df.shape[1]} columns")
df.head()

Saved .data_cache/bank_marketing.parquet — 45211 rows, 17 columns

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,0
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,0
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,0
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,0
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,0

## The config

Every dscompanion run starts with a `PipelineConfig` — one object describing the
whole pipeline. Here's the smallest one that works: a data source, a target column,
and a task type. Everything else (split strategy, feature processing, algorithm choice,
evaluation) falls back to sensible defaults.

In [3]:
from dscompanion.pipeline import PipelineConfig, PipelineRunner

cfg = PipelineConfig(
    name="getting_started",
    data={"path": str(data_path), "format": "parquet", "target": "y"},
    model={"task": "classification"},
)
result = PipelineRunner(cfg).run()

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  PipelineRunner  |  getting_started  v1.0

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  Owner: unset  |  Task: classification  |  Algorithm: xgboost

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  Run directory: reports/20260913_111939

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  [1/13] Loading data

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner         Loaded 45211 rows × 17 columns

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  [2/13] Splitting data

2026-09-13 11:19:39  INFO      dscompanion.split.splitter  Splitting 45,211 rows  strategy='stratified'

2026-09-13 11:19:39  INFO      dscompanion.split.splitter
DataSplit — strategy='stratified'  target='y'
  n_features : 16
  train   :  32,551 rows  event_rate=0.117
  val     :   3,617 rows  event_rate=0.117
  test    :   9,043 rows  event_rate=0.117
  oot     :       0 rows  event_rate=0.000

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  [3/13] EDA

2026-09-13 11:19:39  INFO      dscompanion.eda.report  EDAReport.run_all — starting univariate

2026-09-13 11:19:39  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:39  INFO      dscompanion.eda.report  EDAReport.run_all — bivariate

2026-09-13 11:19:39  INFO      dscompanion.eda.bivariate  BivariateAnalyser.fit — 32551 rows, 16 features

2026-09-13 11:19:39  INFO      dscompanion.eda.report  EDAReport.run_all — multivariate

2026-09-13 11:19:39  INFO      dscompanion.eda.multivariate  MultivariateAnalyser.fit — 32551 rows, 7 numeric columns

2026-09-13 11:19:39  INFO      dscompanion.eda.report  EDAReport.run_all — missingness

2026-09-13 11:19:39  INFO      dscompanion.eda.missingness  MissingnessAnalyser fitted — 500 rows, 16 columns, 4 with partial missingness

2026-09-13 11:19:39  INFO      dscompanion.eda.report  EDAReport.run_all — complete

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner         EDA complete

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  [4/13] Target treatment

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  [5/13] Feature processing (impute → encode → scale)

2026-09-13 11:19:39  INFO      dscompanion.features.imputer  SmartImputer fitted — 4 cols imputed, 0 indicators

2026-09-13 11:19:39  WARNING   dscompanion.features.leakage_guard  WARNING — 'day_of_week' name contains target string

2026-09-13 11:19:39  WARNING   dscompanion.features.leakage_guard  WARNING — 'pdays' name contains target string

2026-09-13 11:19:39  INFO      dscompanion.features.pipeline  Leakage check — 0 critical, 2 warnings

2026-09-13 11:19:39  INFO      dscompanion.features.encoder  OrdinalEncoder fitted — cols=9

2026-09-13 11:19:39  INFO      dscompanion.features.scaler  SmartScaler fitted — strategy=none, 16 numeric cols

2026-09-13 11:19:39  INFO      dscompanion.features.pipeline  FeatureProcessingPipeline fitted — 16 output features

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  [6/13] Feature selection

2026-09-13 11:19:39  INFO      dscompanion.selection.feature_selectors  NullRateSelector: removed 0 / 16 features

2026-09-13 11:19:39  INFO      dscompanion.selection.selection_pipeline  NullRateSelector: 16 → 16 features

2026-09-13 11:19:39  INFO      dscompanion.selection.feature_selectors  ConstantSelector: removed 0 / 16 features

2026-09-13 11:19:39  INFO      dscompanion.selection.selection_pipeline  ConstantSelector: 16 → 16 features

2026-09-13 11:19:39  INFO      dscompanion.selection.feature_selectors  CardinalitySelector: removed 0 / 16 features

2026-09-13 11:19:39  INFO      dscompanion.selection.selection_pipeline  CardinalitySelector: 16 → 16 features

2026-09-13 11:19:39  INFO      dscompanion.selection.feature_selectors  CorrelationSelector: removed 0 / 16 features

2026-09-13 11:19:39  INFO      dscompanion.selection.selection_pipeline  CorrelationSelector: 16 → 16 features

2026-09-13 11:19:39  INFO      dscompanion.selection.feature_selectors  IVSelector: removed 6 / 16 features (threshold=0.0200)

2026-09-13 11:19:39  INFO      dscompanion.selection.selection_pipeline  IVSelector: 16 → 10 features

2026-09-13 11:19:39  INFO      dscompanion.selection.selection_pipeline  FeatureSelectionPipeline: 16 → 10 features retained

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner         Features: 16 → 10 (removed 6)

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  [7/13] Imbalance handling

2026-09-13 11:19:39  INFO      dscompanion.pipeline.runner  [8/13] Training xgboost

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:19:40] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:19:40  INFO      dscompanion.models.base  ClassificationModel fitted in 0.80s on 32551 rows x 10 cols

2026-09-13 11:19:40  INFO      dscompanion.pipeline.runner  [9/13] Tuning skipped (tuning.enabled=False)

2026-09-13 11:19:40  INFO      dscompanion.pipeline.runner  [10/13] Evaluating

2026-09-13 11:19:40  INFO      dscompanion.pipeline.runner  [11/13] Calibration

2026-09-13 11:19:40  INFO      dscompanion.calibration.calibrator  Calibrator fitted — method=isotonic, ECE: 0.0120 → 0.0001

2026-09-13 11:19:40  INFO      dscompanion.models.base  Model saved to reports/20260913_111939/model/getting_started_v1.0_model.joblib

2026-09-13 11:19:40  INFO      dscompanion.pipeline.runner  [12/13] SHAP skipped (explain.shap_enabled=False)

2026-09-13 11:19:40  INFO      dscompanion.pipeline.runner  [12/13] Permutation importance skipped (explain.permutation_enabled=False)

2026-09-13 11:19:40  INFO      dscompanion.pipeline.runner  [13/13] Generating report + logging run

2026-09-13 11:19:41  INFO      dscompanion.docs.model_card  ModelCard generated — 14 sections

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  Run started — 20260913 (getting_started_v1.0) tags={'owner': '', 'algorithm': 'xgboost', 'task': 'classification'}

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  artifact reports/20260913_111939/config.yaml -> config

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric train_f1=0.619107 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric train_precision=0.756061 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric train_recall=0.52416 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric train_roc_auc=0.950745 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric train_gini=0.901489 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric train_ks_statistic=0.76616 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric train_log_loss=0.178049 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric test_f1=0.501399 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric test_precision=0.61454 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric test_recall=0.42344 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric test_roc_auc=0.916387 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric test_gini=0.832773 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric test_ks_statistic=0.7046 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric test_log_loss=0.218092 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric test_psi=0.001125 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric val_f1=0.498592 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric val_precision=0.616725 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric val_recall=0.41844 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric val_roc_auc=0.917421 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric val_gini=0.834841 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric val_ks_statistic=0.699113 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric val_log_loss=0.215935 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric val_psi=0.001947 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric features_before_selection=16 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  metric features_after_selection=10 step=None

2026-09-13 11:19:41  INFO      dscompanion.tracking.run_context  params {'objective': 'binary:logistic', 'base_score': 'None', 'booster': 'None', 'callbacks': 'None', 'colsample_bylevel': 'None', 'colsample_bynode': 'None', 'colsample_bytree': '0.8', 'device': 'None', 'early_stopping_rounds': '20', 'enable_categorical': 'False', 'eval_metric': 'auc', 'feature_types': 'None', 'feature_weights': 'None', 'gamma': 'None', 'grow_policy': 'None', 'importance_type': 'None', 'interaction_constraints': 'None', 'learning_rate': '0.05', 'max_bin': 'None', 'max_cat_threshold': 'None', 'max_cat_to_onehot': 'None', 'max_delta_step': 'None', 'max_depth': '6', 'max_leaves': 'None', 'min_child_weight': '5', 'missing': 'nan', 'monotone_constraints': 'None', 'multi_strategy': 'None', 'n_estimators': '300', 'n_jobs': '-1', 'num_parallel_tree': 'None', 'random_state': '42', 'reg_alpha': '0.1', 'reg_lambda': '1.0', 'sampling_method': 'None', 'scale_pos_weight': '1', 'subsample': '0.8', 'tree_method': 'None', 'validate_parameters': 'None', 'verbosity': 'None', 'class_weight': '{0: 0.5662422154959469, 1: 4.274028361344538}'}

2026-09-13 11:19:41  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:41  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:41  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:41  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:42  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:42  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:43  INFO      dscompanion.docs.model_card  ModelCard (xlsx) → reports/20260913_111939/reports/getting_started_v1.0_model_card.xlsx

2026-09-13 11:19:43  INFO      dscompanion.tracking.run_context  artifact reports/20260913_111939/reports/getting_started_v1.0_model_card.xlsx -> excel_report

2026-09-13 11:19:43  INFO      dscompanion.pipeline.runner  Excel model card written → reports/20260913_111939/reports/getting_started_v1.0_model_card.xlsx

2026-09-13 11:19:43  INFO      dscompanion.tracking.run_context  Run finished — 20260913

2026-09-13 11:19:43  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:19:43  INFO      dscompanion.pipeline.runner  Pipeline complete — 3.9s  |  Run: 20260913_111939

2026-09-13 11:19:43  INFO      dscompanion.pipeline.runner  Report: n/a

2026-09-13 11:19:43  INFO      dscompanion.pipeline.runner  ============================================================

## What just happened

`PipelineRunner.run()` did everything in one call: loaded the data, split it into
train/test, ran EDA, processed features (imputation, encoding, scaling), selected
features, trained a model, and evaluated it. The returned `result` carries every
artifact from that run.

In [4]:
result.metrics

    split        metric     value
0   train            f1  0.619107
1   train     precision  0.756061
2   train        recall  0.524160
3   train       roc_auc  0.950745
4   train          gini  0.901489
5   train  ks_statistic  0.766160
6   train      log_loss  0.178049
7    test            f1  0.501399
8    test     precision  0.614540
9    test        recall  0.423440
10   test       roc_auc  0.916387
11   test          gini  0.832773
12   test  ks_statistic  0.704600
13   test      log_loss  0.218092
14   test           psi  0.001125
15    val            f1  0.498592
16    val     precision  0.616725
17    val        recall  0.418440
18    val       roc_auc  0.917421
19    val          gini  0.834841
20    val  ks_statistic  0.699113
21    val      log_loss  0.215935
22    val           psi  0.001947

`result.metrics` is a tidy (long-format) table: one row per `(split, metric)` pair,
with the value in the `value` column. That shape stays consistent across every task
dscompanion supports — classification, regression, and clustering all return metrics
this way, just with different metric names.

Below: the fitted model itself, and where this run's artifacts (logs, reports, the
trained model file) were written on disk.

In [5]:
print(result.model)
print(result.run_dir)

<dscompanion.models.classification.ClassificationModel object at 0x12d1286e0>
reports/20260913_111939

## Next

[`02_classification_bank_marketing.ipynb`](02_classification_bank_marketing.ipynb) goes
much deeper on this same dataset: EDA reports, why the split strategy matters, comparing
multiple algorithms via the leaderboard, hyperparameter tuning, explainability (SHAP and
permutation importance), and exporting a governance-ready model card.