# Classification Walkthrough: Bank Marketing

The deepest tour of `dscompanion` in this notebook set. We'll use the UCI **Bank
Marketing** dataset — 45,211 records from a Portuguese bank's phone marketing campaign
for term deposits — to walk through EDA, feature processing, splitting strategy,
multi-algorithm comparison (the leaderboard), hyperparameter tuning, explainability,
and exporting a governance-ready model card.

Why this dataset suits classification well: the target `y` (did the client subscribe?)
is heavily imbalanced (most calls don't convert), and the features are a realistic mix
of numeric (`age`, `balance`, `duration`) and categorical (`job`, `marital`, `education`)
columns — exactly the kind of tabular data dscompanion is built for.

See [`README.md`](README.md) for the full notebook index.

In [1]:
!pip install -q dscompanion[notebooks]

zsh:1: no matches found: dscompanion[notebooks]

## Fetch the dataset

Fetched once, then cached locally as parquet — `notebooks/.data_cache/` is gitignored,
so this never gets committed.

One thing worth doing up front: dscompanion's classification models expect a
**numeric** target (`0`/`1`), not a categorical string label — the raw `y` column here
is `"yes"`/`"no"`, so we map it before saving.

In [2]:
from pathlib import Path
import pandas as pd
from ucimlrepo import fetch_ucirepo

cache_dir = Path(".data_cache")
cache_dir.mkdir(exist_ok=True)
data_path = cache_dir / "bank_marketing.parquet"

if not data_path.exists():
    ds = fetch_ucirepo(id=222)
    df = ds.data.features.copy()
    df["y"] = ds.data.targets["y"].map({"yes": 1, "no": 0})
    df.to_parquet(data_path, index=False)
else:
    df = pd.read_parquet(data_path)

print(f"{df.shape[0]} rows, {df.shape[1]} columns")
print("Target balance:")
print(df["y"].value_counts(normalize=True))

45211 rows, 17 columns
Target balance:
y
0    0.883015
1    0.116985
Name: proportion, dtype: float64

## EDA and reporting

`PipelineConfig`'s EDA stage runs automatically as part of `PipelineRunner.run()` — no
separate call needed. Setting `reporting.html_report=True` writes a full interactive EDA
report (univariate distributions, bivariate relationships against the target, correlation
structure) to disk alongside the run's other artifacts.

## Splitting strategy

`SplitConfig(method="stratified", ...)` keeps the train/val/test target distribution
consistent — important here since `y` is imbalanced enough that a plain random split
could leave one split with meaningfully fewer positive examples than another.

In [3]:
from dscompanion.pipeline import PipelineConfig, PipelineRunner

cfg = PipelineConfig(
    name="bank_marketing_classification",
    data={"path": str(data_path), "format": "parquet", "target": "y"},
    split={"method": "stratified", "test_size": 0.2, "val_size": 0.1},
    model={"task": "classification", "algorithm": "xgboost"},
    reporting={"output_dir": "reports", "html_report": True},
)
result = PipelineRunner(cfg).run()
result.metrics

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  PipelineRunner  |  bank_marketing_classification  v1.0

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  Owner: unset  |  Task: classification  |  Algorithm: xgboost

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:19:54  WARNING   dscompanion.pipeline.runner  Non-default config choices (will appear in report):

2026-09-13 11:19:54  WARNING   dscompanion.pipeline.runner    ⚠  reporting.html_report = True  (default: False)

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  Run directory: reports/20260913_111954

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  [1/13] Loading data

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner         Loaded 45211 rows × 17 columns

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  [2/13] Splitting data

2026-09-13 11:19:54  INFO      dscompanion.split.splitter  Splitting 45,211 rows  strategy='stratified'

2026-09-13 11:19:54  INFO      dscompanion.split.splitter
DataSplit — strategy='stratified'  target='y'
  n_features : 16
  train   :  32,551 rows  event_rate=0.117
  val     :   3,617 rows  event_rate=0.117
  test    :   9,043 rows  event_rate=0.117
  oot     :       0 rows  event_rate=0.000

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  [3/13] EDA

2026-09-13 11:19:54  INFO      dscompanion.eda.report  EDAReport.run_all — starting univariate

2026-09-13 11:19:54  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:54  INFO      dscompanion.eda.report  EDAReport.run_all — bivariate

2026-09-13 11:19:54  INFO      dscompanion.eda.bivariate  BivariateAnalyser.fit — 32551 rows, 16 features

2026-09-13 11:19:54  INFO      dscompanion.eda.report  EDAReport.run_all — multivariate

2026-09-13 11:19:54  INFO      dscompanion.eda.multivariate  MultivariateAnalyser.fit — 32551 rows, 7 numeric columns

2026-09-13 11:19:54  INFO      dscompanion.eda.report  EDAReport.run_all — missingness

2026-09-13 11:19:54  INFO      dscompanion.eda.missingness  MissingnessAnalyser fitted — 500 rows, 16 columns, 4 with partial missingness

2026-09-13 11:19:54  INFO      dscompanion.eda.report  EDAReport.run_all — complete

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner         EDA complete

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  [4/13] Target treatment

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  [5/13] Feature processing (impute → encode → scale)

2026-09-13 11:19:54  INFO      dscompanion.features.imputer  SmartImputer fitted — 4 cols imputed, 0 indicators

2026-09-13 11:19:54  WARNING   dscompanion.features.leakage_guard  WARNING — 'day_of_week' name contains target string

2026-09-13 11:19:54  WARNING   dscompanion.features.leakage_guard  WARNING — 'pdays' name contains target string

2026-09-13 11:19:54  INFO      dscompanion.features.pipeline  Leakage check — 0 critical, 2 warnings

2026-09-13 11:19:54  INFO      dscompanion.features.encoder  OrdinalEncoder fitted — cols=9

2026-09-13 11:19:54  INFO      dscompanion.features.scaler  SmartScaler fitted — strategy=none, 16 numeric cols

2026-09-13 11:19:54  INFO      dscompanion.features.pipeline  FeatureProcessingPipeline fitted — 16 output features

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  [6/13] Feature selection

2026-09-13 11:19:54  INFO      dscompanion.selection.feature_selectors  NullRateSelector: removed 0 / 16 features

2026-09-13 11:19:54  INFO      dscompanion.selection.selection_pipeline  NullRateSelector: 16 → 16 features

2026-09-13 11:19:54  INFO      dscompanion.selection.feature_selectors  ConstantSelector: removed 0 / 16 features

2026-09-13 11:19:54  INFO      dscompanion.selection.selection_pipeline  ConstantSelector: 16 → 16 features

2026-09-13 11:19:54  INFO      dscompanion.selection.feature_selectors  CardinalitySelector: removed 0 / 16 features

2026-09-13 11:19:54  INFO      dscompanion.selection.selection_pipeline  CardinalitySelector: 16 → 16 features

2026-09-13 11:19:54  INFO      dscompanion.selection.feature_selectors  CorrelationSelector: removed 0 / 16 features

2026-09-13 11:19:54  INFO      dscompanion.selection.selection_pipeline  CorrelationSelector: 16 → 16 features

2026-09-13 11:19:54  INFO      dscompanion.selection.feature_selectors  IVSelector: removed 6 / 16 features (threshold=0.0200)

2026-09-13 11:19:54  INFO      dscompanion.selection.selection_pipeline  IVSelector: 16 → 10 features

2026-09-13 11:19:54  INFO      dscompanion.selection.selection_pipeline  FeatureSelectionPipeline: 16 → 10 features retained

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner         Features: 16 → 10 (removed 6)

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  [7/13] Imbalance handling

2026-09-13 11:19:54  INFO      dscompanion.pipeline.runner  [8/13] Training xgboost

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:19:54] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:19:55  INFO      dscompanion.models.base  ClassificationModel fitted in 0.80s on 32551 rows x 10 cols

2026-09-13 11:19:55  INFO      dscompanion.pipeline.runner  [9/13] Tuning skipped (tuning.enabled=False)

2026-09-13 11:19:55  INFO      dscompanion.pipeline.runner  [10/13] Evaluating

2026-09-13 11:19:55  INFO      dscompanion.pipeline.runner  [11/13] Calibration

2026-09-13 11:19:55  INFO      dscompanion.calibration.calibrator  Calibrator fitted — method=isotonic, ECE: 0.0120 → 0.0001

2026-09-13 11:19:55  INFO      dscompanion.models.base  Model saved to reports/20260913_111954/model/bank_marketing_classification_v1.0_model.joblib

2026-09-13 11:19:55  INFO      dscompanion.pipeline.runner  [12/13] SHAP skipped (explain.shap_enabled=False)

2026-09-13 11:19:55  INFO      dscompanion.pipeline.runner  [12/13] Permutation importance skipped (explain.permutation_enabled=False)

2026-09-13 11:19:55  INFO      dscompanion.pipeline.runner  [13/13] Generating report + logging run

2026-09-13 11:19:55  INFO      dscompanion.docs.model_card  ModelCard generated — 14 sections

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  Run started — 20260913 (bank_marketing_classification_v1.0) tags={'owner': '', 'algorithm': 'xgboost', 'task': 'classification'}

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  artifact reports/20260913_111954/config.yaml -> config

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric train_f1=0.619107 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric train_precision=0.756061 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric train_recall=0.52416 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric train_roc_auc=0.950745 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric train_gini=0.901489 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric train_ks_statistic=0.76616 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric train_log_loss=0.178049 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric test_f1=0.501399 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric test_precision=0.61454 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric test_recall=0.42344 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric test_roc_auc=0.916387 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric test_gini=0.832773 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric test_ks_statistic=0.7046 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric test_log_loss=0.218092 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric test_psi=0.001125 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric val_f1=0.498592 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric val_precision=0.616725 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric val_recall=0.41844 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric val_roc_auc=0.917421 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric val_gini=0.834841 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric val_ks_statistic=0.699113 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric val_log_loss=0.215935 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric val_psi=0.001947 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric features_before_selection=16 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  metric features_after_selection=10 step=None

2026-09-13 11:19:55  INFO      dscompanion.tracking.run_context  params {'objective': 'binary:logistic', 'base_score': 'None', 'booster': 'None', 'callbacks': 'None', 'colsample_bylevel': 'None', 'colsample_bynode': 'None', 'colsample_bytree': '0.8', 'device': 'None', 'early_stopping_rounds': '20', 'enable_categorical': 'False', 'eval_metric': 'auc', 'feature_types': 'None', 'feature_weights': 'None', 'gamma': 'None', 'grow_policy': 'None', 'importance_type': 'None', 'interaction_constraints': 'None', 'learning_rate': '0.05', 'max_bin': 'None', 'max_cat_threshold': 'None', 'max_cat_to_onehot': 'None', 'max_delta_step': 'None', 'max_depth': '6', 'max_leaves': 'None', 'min_child_weight': '5', 'missing': 'nan', 'monotone_constraints': 'None', 'multi_strategy': 'None', 'n_estimators': '300', 'n_jobs': '-1', 'num_parallel_tree': 'None', 'random_state': '42', 'reg_alpha': '0.1', 'reg_lambda': '1.0', 'sampling_method': 'None', 'scale_pos_weight': '1', 'subsample': '0.8', 'tree_method': 'None', 'validate_parameters': 'None', 'verbosity': 'None', 'class_weight': '{0: 0.5662422154959469, 1: 4.274028361344538}'}

2026-09-13 11:19:55  INFO      dscompanion.pipeline.runner  config_deviations: reporting.html_report=True (default False)

2026-09-13 11:19:55  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:55  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:55  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:55  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:57  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:57  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:58  INFO      dscompanion.docs.model_card  ModelCard (xlsx) → reports/20260913_111954/reports/bank_marketing_classification_v1.0_model_card.xlsx

2026-09-13 11:19:58  INFO      dscompanion.tracking.run_context  artifact reports/20260913_111954/reports/bank_marketing_classification_v1.0_model_card.xlsx -> excel_report

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  Excel model card written → reports/20260913_111954/reports/bank_marketing_classification_v1.0_model_card.xlsx

2026-09-13 11:19:58  INFO      dscompanion.docs.html_widgets  Fetching Bootstrap 5 for self-contained model card report

2026-09-13 11:19:58  INFO      dscompanion.docs.html_widgets  Bootstrap assets: embedded

2026-09-13 11:19:58  INFO      dscompanion.docs.model_card  ModelCard (html) → reports/20260913_111954/reports/bank_marketing_classification_v1.0_model_card.html

2026-09-13 11:19:58  INFO      dscompanion.tracking.run_context  artifact reports/20260913_111954/reports/bank_marketing_classification_v1.0_model_card.html -> report

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  HTML report written → reports/20260913_111954/reports/bank_marketing_classification_v1.0_model_card.html

2026-09-13 11:19:58  INFO      dscompanion.tracking.run_context  Run finished — 20260913

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  Pipeline complete — 4.3s  |  Run: 20260913_111954

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  Report: reports/20260913_111954/reports/bank_marketing_classification_v1.0_model_card.html

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  ============================================================

    split        metric     value
0   train            f1  0.619107
1   train     precision  0.756061
2   train        recall  0.524160
3   train       roc_auc  0.950745
4   train          gini  0.901489
5   train  ks_statistic  0.766160
6   train      log_loss  0.178049
7    test            f1  0.501399
8    test     precision  0.614540
9    test        recall  0.423440
10   test       roc_auc  0.916387
11   test          gini  0.832773
12   test  ks_statistic  0.704600
13   test      log_loss  0.218092
14   test           psi  0.001125
15    val            f1  0.498592
16    val     precision  0.616725
17    val        recall  0.418440
18    val       roc_auc  0.917421
19    val          gini  0.834841
20    val  ks_statistic  0.699113
21    val      log_loss  0.215935
22    val           psi  0.001947

`result.metrics` is a tidy (long-format) table: one row per `(split, metric)` pair. This
shape is shared by every task dscompanion supports — only the metric names differ.
Pivoting makes it easier to compare train vs. test at a glance:

In [4]:
result.metrics.pivot(index="metric", columns="split", values="value")

split             test     train       val
metric
f1            0.501399  0.619107  0.498592
gini          0.832773  0.901489  0.834841
ks_statistic  0.704600  0.766160  0.699113
log_loss      0.218092  0.178049  0.215935
precision     0.614540  0.756061  0.616725
psi           0.001125       NaN  0.001947
recall        0.423440  0.524160  0.418440
roc_auc       0.916387  0.950745  0.917421

In [5]:
# The HTML EDA report and other run artifacts live under result.run_dir
print(result.run_dir)
list(result.run_dir.glob("**/*.html"))[:5]

reports/20260913_111954

[PosixPath('reports/20260913_111954/reports/bank_marketing_classification_v1.0_model_card.html')]

## Comparing algorithms: the leaderboard

Rather than committing to `xgboost` up front, `LeaderboardConfig(enabled=True)` trains
and compares every algorithm dscompanion supports for this task, ranks them, and
promotes the top performer — `config.model.algorithm` is updated in place to match, so
everything downstream (tuning, explainability, the model card) uses the winner.

In [6]:
cfg_lb = PipelineConfig(
    name="bank_marketing_leaderboard",
    data={"path": str(data_path), "format": "parquet", "target": "y"},
    split={"method": "stratified", "test_size": 0.2, "val_size": 0.1},
    model={"task": "classification", "algorithm": "xgboost"},
    leaderboard={"enabled": True},
    reporting={"output_dir": "reports", "html_report": False},
)
result_lb = PipelineRunner(cfg_lb).run()

print("Winning algorithm:", cfg_lb.model.algorithm)
result_lb.leaderboard.leaderboard_

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  PipelineRunner  |  bank_marketing_leaderboard  v1.0

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  Owner: unset  |  Task: classification  |  Algorithm: xgboost

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:19:58  WARNING   dscompanion.pipeline.runner  Non-default config choices (will appear in report):

2026-09-13 11:19:58  WARNING   dscompanion.pipeline.runner    ⚠  leaderboard.enabled = True  (default: False)

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  Run directory: reports/20260913_111958

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  [1/13] Loading data

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner         Loaded 45211 rows × 17 columns

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  [2/13] Splitting data

2026-09-13 11:19:58  INFO      dscompanion.split.splitter  Splitting 45,211 rows  strategy='stratified'

2026-09-13 11:19:58  INFO      dscompanion.split.splitter
DataSplit — strategy='stratified'  target='y'
  n_features : 16
  train   :  32,551 rows  event_rate=0.117
  val     :   3,617 rows  event_rate=0.117
  test    :   9,043 rows  event_rate=0.117
  oot     :       0 rows  event_rate=0.000

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  [3/13] EDA

2026-09-13 11:19:58  INFO      dscompanion.eda.report  EDAReport.run_all — starting univariate

2026-09-13 11:19:58  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:19:58  INFO      dscompanion.eda.report  EDAReport.run_all — bivariate

2026-09-13 11:19:58  INFO      dscompanion.eda.bivariate  BivariateAnalyser.fit — 32551 rows, 16 features

2026-09-13 11:19:58  INFO      dscompanion.eda.report  EDAReport.run_all — multivariate

2026-09-13 11:19:58  INFO      dscompanion.eda.multivariate  MultivariateAnalyser.fit — 32551 rows, 7 numeric columns

2026-09-13 11:19:58  INFO      dscompanion.eda.report  EDAReport.run_all — missingness

2026-09-13 11:19:58  INFO      dscompanion.eda.missingness  MissingnessAnalyser fitted — 500 rows, 16 columns, 4 with partial missingness

2026-09-13 11:19:58  INFO      dscompanion.eda.report  EDAReport.run_all — complete

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner         EDA complete

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  [4/13] Target treatment

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  [5/13] Feature processing (impute → encode → scale)

2026-09-13 11:19:58  INFO      dscompanion.features.imputer  SmartImputer fitted — 4 cols imputed, 0 indicators

2026-09-13 11:19:58  WARNING   dscompanion.features.leakage_guard  WARNING — 'day_of_week' name contains target string

2026-09-13 11:19:58  WARNING   dscompanion.features.leakage_guard  WARNING — 'pdays' name contains target string

2026-09-13 11:19:58  INFO      dscompanion.features.pipeline  Leakage check — 0 critical, 2 warnings

2026-09-13 11:19:58  INFO      dscompanion.features.encoder  OrdinalEncoder fitted — cols=9

2026-09-13 11:19:58  INFO      dscompanion.features.scaler  SmartScaler fitted — strategy=none, 16 numeric cols

2026-09-13 11:19:58  INFO      dscompanion.features.pipeline  FeatureProcessingPipeline fitted — 16 output features

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  [6/13] Feature selection

2026-09-13 11:19:58  INFO      dscompanion.selection.feature_selectors  NullRateSelector: removed 0 / 16 features

2026-09-13 11:19:58  INFO      dscompanion.selection.selection_pipeline  NullRateSelector: 16 → 16 features

2026-09-13 11:19:58  INFO      dscompanion.selection.feature_selectors  ConstantSelector: removed 0 / 16 features

2026-09-13 11:19:58  INFO      dscompanion.selection.selection_pipeline  ConstantSelector: 16 → 16 features

2026-09-13 11:19:58  INFO      dscompanion.selection.feature_selectors  CardinalitySelector: removed 0 / 16 features

2026-09-13 11:19:58  INFO      dscompanion.selection.selection_pipeline  CardinalitySelector: 16 → 16 features

2026-09-13 11:19:58  INFO      dscompanion.selection.feature_selectors  CorrelationSelector: removed 0 / 16 features

2026-09-13 11:19:58  INFO      dscompanion.selection.selection_pipeline  CorrelationSelector: 16 → 16 features

2026-09-13 11:19:58  INFO      dscompanion.selection.feature_selectors  IVSelector: removed 6 / 16 features (threshold=0.0200)

2026-09-13 11:19:58  INFO      dscompanion.selection.selection_pipeline  IVSelector: 16 → 10 features

2026-09-13 11:19:58  INFO      dscompanion.selection.selection_pipeline  FeatureSelectionPipeline: 16 → 10 features retained

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner         Features: 16 → 10 (removed 6)

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  [7/13] Imbalance handling

2026-09-13 11:19:58  INFO      dscompanion.pipeline.runner  [8/13] Leaderboard: comparing algorithms (model.algorithm=xgboost is ignored)

2026-09-13 11:19:59  INFO      dscompanion.models.base  ClassificationModel fitted in 0.82s on 32551 rows x 10 cols

[LightGBM] [Info] Number of positive: 3808, number of negative: 28743
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002057 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 716
[LightGBM] [Info] Number of data points in the train set: 32551, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116986 -> initscore=-2.021290
[LightGBM] [Info] Start training from score -2.021290

2026-09-13 11:20:01  INFO      dscompanion.models.base  ClassificationModel fitted in 1.12s on 32551 rows x 10 cols

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2026-09-13 11:20:05  INFO      dscompanion.models.base  ClassificationModel fitted in 4.02s on 32551 rows x 10 cols

2026-09-13 11:20:05  INFO      dscompanion.models.base  ClassificationModel fitted in 0.52s on 32551 rows x 10 cols

2026-09-13 11:20:12  INFO      dscompanion.models.base  ClassificationModel fitted in 6.05s on 32551 rows x 10 cols

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/sklearn/svm/_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

2026-09-13 11:20:42  INFO      dscompanion.models.base  ClassificationModel fitted in 29.60s on 32551 rows x 10 cols

2026-09-13 11:21:09  INFO      dscompanion.models.base  ClassificationModel fitted in 0.01s on 32551 rows x 10 cols

2026-09-13 11:21:09  INFO      dscompanion.models.base  ClassificationModel fitted in 0.05s on 32551 rows x 10 cols

2026-09-13 11:21:09  INFO      dscompanion.models.base  ClassificationModel fitted in 0.19s on 32551 rows x 10 cols

2026-09-13 11:21:10  INFO      dscompanion.models.base  ClassificationModel fitted in 1.09s on 32551 rows x 10 cols

2026-09-13 11:21:11  INFO      dscompanion.models.base  ClassificationModel fitted in 0.00s on 32551 rows x 10 cols

2026-09-13 11:21:11  INFO      dscompanion.leaderboard.leaderboard  Leaderboard: 11/11 algorithms succeeded (eval_split=val, sort_metric=roc_auc)

2026-09-13 11:21:11  INFO      dscompanion.pipeline.runner         Leaderboard winner: xgboost

2026-09-13 11:21:11  INFO      dscompanion.pipeline.runner  [9/13] Tuning skipped (tuning.enabled=False)

2026-09-13 11:21:11  INFO      dscompanion.pipeline.runner  [10/13] Evaluating

2026-09-13 11:21:11  INFO      dscompanion.pipeline.runner  [11/13] Calibration

2026-09-13 11:21:11  INFO      dscompanion.calibration.calibrator  Calibrator fitted — method=isotonic, ECE: 0.0120 → 0.0001

2026-09-13 11:21:11  INFO      dscompanion.models.base  Model saved to reports/20260913_111958/model/bank_marketing_leaderboard_v1.0_model.joblib

2026-09-13 11:21:11  INFO      dscompanion.pipeline.runner  [12/13] SHAP skipped (explain.shap_enabled=False)

2026-09-13 11:21:11  INFO      dscompanion.pipeline.runner  [12/13] Permutation importance skipped (explain.permutation_enabled=False)

2026-09-13 11:21:11  INFO      dscompanion.pipeline.runner  [13/13] Generating report + logging run

2026-09-13 11:21:11  INFO      dscompanion.docs.model_card  ModelCard generated — 14 sections

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  Run started — 20260913 (bank_marketing_leaderboard_v1.0) tags={'owner': '', 'algorithm': 'xgboost', 'task': 'classification'}

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  artifact reports/20260913_111958/config.yaml -> config

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric train_f1=0.619107 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric train_precision=0.756061 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric train_recall=0.52416 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric train_roc_auc=0.950745 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric train_gini=0.901489 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric train_ks_statistic=0.76616 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric train_log_loss=0.178049 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric test_f1=0.501399 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric test_precision=0.61454 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric test_recall=0.42344 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric test_roc_auc=0.916387 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric test_gini=0.832773 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric test_ks_statistic=0.7046 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric test_log_loss=0.218092 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric test_psi=0.001125 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric val_f1=0.498592 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric val_precision=0.616725 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric val_recall=0.41844 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric val_roc_auc=0.917421 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric val_gini=0.834841 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric val_ks_statistic=0.699113 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric val_log_loss=0.215935 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric val_psi=0.001947 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric features_before_selection=16 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  metric features_after_selection=10 step=None

2026-09-13 11:21:11  INFO      dscompanion.tracking.run_context  params {'objective': 'binary:logistic', 'base_score': 'None', 'booster': 'None', 'callbacks': 'None', 'colsample_bylevel': 'None', 'colsample_bynode': 'None', 'colsample_bytree': '0.8', 'device': 'None', 'early_stopping_rounds': '20', 'enable_categorical': 'False', 'eval_metric': 'auc', 'feature_types': 'None', 'feature_weights': 'None', 'gamma': 'None', 'grow_policy': 'None', 'importance_type': 'None', 'interaction_constraints': 'None', 'learning_rate': '0.05', 'max_bin': 'None', 'max_cat_threshold': 'None', 'max_cat_to_onehot': 'None', 'max_delta_step': 'None', 'max_depth': '6', 'max_leaves': 'None', 'min_child_weight': '5', 'missing': 'nan', 'monotone_constraints': 'None', 'multi_strategy': 'None', 'n_estimators': '300', 'n_jobs': '-1', 'num_parallel_tree': 'None', 'random_state': '42', 'reg_alpha': '0.1', 'reg_lambda': '1.0', 'sampling_method': 'None', 'scale_pos_weight': '1', 'subsample': '0.8', 'tree_method': 'None', 'validate_parameters': 'None', 'verbosity': 'None'}

2026-09-13 11:21:11  INFO      dscompanion.pipeline.runner  config_deviations: leaderboard.enabled=True (default False)

2026-09-13 11:21:11  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:11  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:11  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:11  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:12  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:12  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:33  INFO      dscompanion.docs.model_card  ModelCard (xlsx) → reports/20260913_111958/reports/bank_marketing_leaderboard_v1.0_model_card.xlsx

2026-09-13 11:21:33  INFO      dscompanion.tracking.run_context  artifact reports/20260913_111958/reports/bank_marketing_leaderboard_v1.0_model_card.xlsx -> excel_report

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  Excel model card written → reports/20260913_111958/reports/bank_marketing_leaderboard_v1.0_model_card.xlsx

2026-09-13 11:21:33  INFO      dscompanion.tracking.run_context  Run finished — 20260913

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  Pipeline complete — 94.9s  |  Run: 20260913_111958

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  Report: n/a

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  ============================================================

Winning algorithm: xgboost

,algorithm,status,fit_time_seconds,error,f1,precision,recall,roc_auc,gini,ks_statistic,log_loss,psi
0,xgboost,ok,0.835,None,0.498592,0.616725,0.418440,0.917421,0.834841,0.699113,0.215935,0.001947
1,lightgbm,ok,1.187,None,0.531714,0.619497,0.465721,0.917003,0.834006,0.698060,0.215405,0.001136
2,gradient_boosting,ok,6.123,None,0.461095,0.590406,0.378251,0.904792,0.809584,0.673358,0.229533,0.002888
3,extra_trees,ok,0.221,None,0.000000,0.000000,0.000000,0.903143,0.806286,0.670495,0.262951,0.002906
4,random_forest,ok,0.565,None,0.405616,0.596330,0.307329,0.902099,0.804198,0.670980,0.232051,0.003127
5,adaboost,ok,1.168,None,0.004695,0.333333,0.002364,0.833609,0.667218,0.523034,0.359184,0.002237
6,decision_tree,ok,0.053,None,0.409160,0.577586,0.316785,0.829123,0.658246,0.533506,0.272666,0.000229
7,naive_bayes,ok,0.008,None,0.352132,0.421053,0.302600,0.818968,0.637937,0.526496,0.562362,0.002094
8,knn,ok,0.045,None,0.256579,0.421622,0.184397,0.709758,0.419515,0.369905,1.739567,0.000450
9,svm,ok,37.731,None,0.018433,0.363636,0.009456,0.690774,0.381547,0.359898,0.362710,0.000701
10,logistic,ok,4.023,None,0.139918,0.539683,0.080378,0.672847,0.345694,0.336453,0.347993,0.003470

## Hyperparameter tuning

`TuningConfig(enabled=True)` runs an Optuna search over the chosen algorithm's
hyperparameter space. `n_trials=20` here keeps this notebook fast to run end-to-end —
production runs would typically use 100-200 trials (see the `TuningConfig` docstring).

In [7]:
cfg_tuned = PipelineConfig(
    name="bank_marketing_tuned",
    data={"path": str(data_path), "format": "parquet", "target": "y"},
    split={"method": "stratified", "test_size": 0.2, "val_size": 0.1},
    model={"task": "classification", "algorithm": "xgboost"},
    tuning={"enabled": True, "n_trials": 20},
    reporting={"output_dir": "reports", "html_report": False},
)
result_tuned = PipelineRunner(cfg_tuned).run()

print("Best params found:")
print(result_tuned.tuner.best_params_)
result_tuned.metrics.pivot(index="metric", columns="split", values="value")

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  PipelineRunner  |  bank_marketing_tuned  v1.0

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  Owner: unset  |  Task: classification  |  Algorithm: xgboost

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:21:33  WARNING   dscompanion.pipeline.runner  Non-default config choices (will appear in report):

2026-09-13 11:21:33  WARNING   dscompanion.pipeline.runner    ⚠  tuning.enabled = True  (default: False)

2026-09-13 11:21:33  WARNING   dscompanion.pipeline.runner    ⚠  tuning.n_trials = 20  (default: 50)

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  Run directory: reports/20260913_112133

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  [1/13] Loading data

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner         Loaded 45211 rows × 17 columns

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  [2/13] Splitting data

2026-09-13 11:21:33  INFO      dscompanion.split.splitter  Splitting 45,211 rows  strategy='stratified'

2026-09-13 11:21:33  INFO      dscompanion.split.splitter
DataSplit — strategy='stratified'  target='y'
  n_features : 16
  train   :  32,551 rows  event_rate=0.117
  val     :   3,617 rows  event_rate=0.117
  test    :   9,043 rows  event_rate=0.117
  oot     :       0 rows  event_rate=0.000

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  [3/13] EDA

2026-09-13 11:21:33  INFO      dscompanion.eda.report  EDAReport.run_all — starting univariate

2026-09-13 11:21:33  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:33  INFO      dscompanion.eda.report  EDAReport.run_all — bivariate

2026-09-13 11:21:33  INFO      dscompanion.eda.bivariate  BivariateAnalyser.fit — 32551 rows, 16 features

2026-09-13 11:21:33  INFO      dscompanion.eda.report  EDAReport.run_all — multivariate

2026-09-13 11:21:33  INFO      dscompanion.eda.multivariate  MultivariateAnalyser.fit — 32551 rows, 7 numeric columns

2026-09-13 11:21:33  INFO      dscompanion.eda.report  EDAReport.run_all — missingness

2026-09-13 11:21:33  INFO      dscompanion.eda.missingness  MissingnessAnalyser fitted — 500 rows, 16 columns, 4 with partial missingness

2026-09-13 11:21:33  INFO      dscompanion.eda.report  EDAReport.run_all — complete

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner         EDA complete

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  [4/13] Target treatment

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  [5/13] Feature processing (impute → encode → scale)

2026-09-13 11:21:33  INFO      dscompanion.features.imputer  SmartImputer fitted — 4 cols imputed, 0 indicators

2026-09-13 11:21:33  WARNING   dscompanion.features.leakage_guard  WARNING — 'day_of_week' name contains target string

2026-09-13 11:21:33  WARNING   dscompanion.features.leakage_guard  WARNING — 'pdays' name contains target string

2026-09-13 11:21:33  INFO      dscompanion.features.pipeline  Leakage check — 0 critical, 2 warnings

2026-09-13 11:21:33  INFO      dscompanion.features.encoder  OrdinalEncoder fitted — cols=9

2026-09-13 11:21:33  INFO      dscompanion.features.scaler  SmartScaler fitted — strategy=none, 16 numeric cols

2026-09-13 11:21:33  INFO      dscompanion.features.pipeline  FeatureProcessingPipeline fitted — 16 output features

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  [6/13] Feature selection

2026-09-13 11:21:33  INFO      dscompanion.selection.feature_selectors  NullRateSelector: removed 0 / 16 features

2026-09-13 11:21:33  INFO      dscompanion.selection.selection_pipeline  NullRateSelector: 16 → 16 features

2026-09-13 11:21:33  INFO      dscompanion.selection.feature_selectors  ConstantSelector: removed 0 / 16 features

2026-09-13 11:21:33  INFO      dscompanion.selection.selection_pipeline  ConstantSelector: 16 → 16 features

2026-09-13 11:21:33  INFO      dscompanion.selection.feature_selectors  CardinalitySelector: removed 0 / 16 features

2026-09-13 11:21:33  INFO      dscompanion.selection.selection_pipeline  CardinalitySelector: 16 → 16 features

2026-09-13 11:21:33  INFO      dscompanion.selection.feature_selectors  CorrelationSelector: removed 0 / 16 features

2026-09-13 11:21:33  INFO      dscompanion.selection.selection_pipeline  CorrelationSelector: 16 → 16 features

2026-09-13 11:21:33  INFO      dscompanion.selection.feature_selectors  IVSelector: removed 6 / 16 features (threshold=0.0200)

2026-09-13 11:21:33  INFO      dscompanion.selection.selection_pipeline  IVSelector: 16 → 10 features

2026-09-13 11:21:33  INFO      dscompanion.selection.selection_pipeline  FeatureSelectionPipeline: 16 → 10 features retained

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner         Features: 16 → 10 (removed 6)

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  [7/13] Imbalance handling

2026-09-13 11:21:33  INFO      dscompanion.pipeline.runner  [8/13] Training xgboost

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:33] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:34  INFO      dscompanion.models.base  ClassificationModel fitted in 0.80s on 32551 rows x 10 cols

2026-09-13 11:21:34  INFO      dscompanion.pipeline.runner  [9/13] Hyperparameter tuning (20 trials)

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:34] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:35  INFO      dscompanion.models.base  ClassificationModel fitted in 0.53s on 32551 rows x 10 cols

2026-09-13 11:21:35  INFO      dscompanion.tuning.backends.optuna_backend  Trial 0 params={'n_estimators': 437, 'max_depth': 9, 'learning_rate': 0.1205712628744377, 'subsample': 0.8394633936788146, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 0.000602521573620386, 'reg_lambda': 0.00019517224641449495, 'min_child_weight': 18} score=0.914993

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:35] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:37  INFO      dscompanion.models.base  ClassificationModel fitted in 2.46s on 32551 rows x 10 cols

2026-09-13 11:21:37  INFO      dscompanion.tuning.backends.optuna_backend  Trial 1 params={'n_estimators': 641, 'max_depth': 7, 'learning_rate': 0.010725209743171997, 'subsample': 0.9879639408647978, 'colsample_bytree': 0.9162213204002109, 'reg_alpha': 0.0011526449540315614, 'reg_lambda': 0.0008111941985431928, 'min_child_weight': 4} score=0.915045

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:37] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:38  INFO      dscompanion.models.base  ClassificationModel fitted in 0.80s on 32551 rows x 10 cols

2026-09-13 11:21:38  INFO      dscompanion.tuning.backends.optuna_backend  Trial 2 params={'n_estimators': 374, 'max_depth': 6, 'learning_rate': 0.04345454109729477, 'subsample': 0.7164916560792167, 'colsample_bytree': 0.8059264473611898, 'reg_alpha': 0.0004982752357076451, 'reg_lambda': 0.0028888383623653178, 'min_child_weight': 8} score=0.916751

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:38] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:40  INFO      dscompanion.models.base  ClassificationModel fitted in 1.53s on 32551 rows x 10 cols

2026-09-13 11:21:40  INFO      dscompanion.tuning.backends.optuna_backend  Trial 3 params={'n_estimators': 510, 'max_depth': 8, 'learning_rate': 0.019721610970574007, 'subsample': 0.8056937753654446, 'colsample_bytree': 0.7962072844310213, 'reg_alpha': 0.00017070728830306665, 'reg_lambda': 0.1090747583515769, 'min_child_weight': 4} score=0.918001

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:40] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:40  INFO      dscompanion.models.base  ClassificationModel fitted in 0.26s on 32551 rows x 10 cols

2026-09-13 11:21:40  INFO      dscompanion.tuning.backends.optuna_backend  Trial 4 params={'n_estimators': 158, 'max_depth': 9, 'learning_rate': 0.26690431824362526, 'subsample': 0.9233589392465844, 'colsample_bytree': 0.6523068845866853, 'reg_alpha': 0.0003078651783619622, 'reg_lambda': 0.2637333993381525, 'min_child_weight': 9} score=0.916634

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:40] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:41  INFO      dscompanion.models.base  ClassificationModel fitted in 0.72s on 32551 rows x 10 cols

2026-09-13 11:21:41  INFO      dscompanion.tuning.backends.optuna_backend  Trial 5 params={'n_estimators': 209, 'max_depth': 6, 'learning_rate': 0.011240768803005551, 'subsample': 0.9637281608315128, 'colsample_bytree': 0.6293899908000085, 'reg_alpha': 0.20540519425388448, 'reg_lambda': 0.0036187233309596225, 'min_child_weight': 11} score=0.901804

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:41] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:41  INFO      dscompanion.models.base  ClassificationModel fitted in 0.37s on 32551 rows x 10 cols

2026-09-13 11:21:41  INFO      dscompanion.tuning.backends.optuna_backend  Trial 6 params={'n_estimators': 592, 'max_depth': 4, 'learning_rate': 0.2705166881899928, 'subsample': 0.9100531293444458, 'colsample_bytree': 0.9697494707820946, 'reg_alpha': 2.979454462591361, 'reg_lambda': 0.09761125443110452, 'min_child_weight': 19} score=0.91433

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:41] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:42  INFO      dscompanion.models.base  ClassificationModel fitted in 0.20s on 32551 rows x 10 cols

2026-09-13 11:21:42  INFO      dscompanion.tuning.backends.optuna_backend  Trial 7 params={'n_estimators': 179, 'max_depth': 4, 'learning_rate': 0.011662890273931383, 'subsample': 0.7301321323053057, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 0.002273762810253686, 'reg_lambda': 1.3921548533046488, 'min_child_weight': 8} score=0.876514

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:42] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:42  INFO      dscompanion.models.base  ClassificationModel fitted in 0.26s on 32551 rows x 10 cols

2026-09-13 11:21:42  INFO      dscompanion.tuning.backends.optuna_backend  Trial 8 params={'n_estimators': 353, 'max_depth': 6, 'learning_rate': 0.016149614799999188, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.5372753218398854, 'reg_alpha': 8.59873733921227, 'reg_lambda': 0.7264803074826723, 'min_child_weight': 4} score=0.89631

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:42] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:42  INFO      dscompanion.models.base  ClassificationModel fitted in 0.41s on 32551 rows x 10 cols

2026-09-13 11:21:42  INFO      dscompanion.tuning.backends.optuna_backend  Trial 9 params={'n_estimators': 104, 'max_depth': 8, 'learning_rate': 0.11069143219393454, 'subsample': 0.8916028672163949, 'colsample_bytree': 0.8856351733429728, 'reg_alpha': 0.00023454342277260534, 'reg_lambda': 0.006199100007802264, 'min_child_weight': 3} score=0.918417

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:43] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:43  INFO      dscompanion.models.base  ClassificationModel fitted in 0.72s on 32551 rows x 10 cols

2026-09-13 11:21:43  INFO      dscompanion.tuning.backends.optuna_backend  Trial 10 params={'n_estimators': 891, 'max_depth': 3, 'learning_rate': 0.08861501021155405, 'subsample': 0.6071847502459278, 'colsample_bytree': 0.8770690800880656, 'reg_alpha': 0.01248505791407006, 'reg_lambda': 6.292942010319496, 'min_child_weight': 1} score=0.909255

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:43] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:44  INFO      dscompanion.models.base  ClassificationModel fitted in 0.84s on 32551 rows x 10 cols

2026-09-13 11:21:44  INFO      dscompanion.tuning.backends.optuna_backend  Trial 11 params={'n_estimators': 806, 'max_depth': 8, 'learning_rate': 0.034593301147901656, 'subsample': 0.8234098923117161, 'colsample_bytree': 0.7923476260453055, 'reg_alpha': 0.00015284684734585583, 'reg_lambda': 0.01989385922739852, 'min_child_weight': 1} score=0.916747

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:44] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:45  INFO      dscompanion.models.base  ClassificationModel fitted in 1.20s on 32551 rows x 10 cols

2026-09-13 11:21:46  INFO      dscompanion.tuning.backends.optuna_backend  Trial 12 params={'n_estimators': 721, 'max_depth': 8, 'learning_rate': 0.024795803650758556, 'subsample': 0.7650970966716663, 'colsample_bytree': 0.856148643942211, 'reg_alpha': 0.005351416165734628, 'reg_lambda': 0.022055966549515183, 'min_child_weight': 5} score=0.919164

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:46] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:46  INFO      dscompanion.models.base  ClassificationModel fitted in 0.36s on 32551 rows x 10 cols

2026-09-13 11:21:46  INFO      dscompanion.tuning.backends.optuna_backend  Trial 13 params={'n_estimators': 733, 'max_depth': 8, 'learning_rate': 0.10911097866235923, 'subsample': 0.7371197153065265, 'colsample_bytree': 0.9885495813070362, 'reg_alpha': 0.007147196996104383, 'reg_lambda': 0.015511394289104665, 'min_child_weight': 14} score=0.916181

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:46] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:47  INFO      dscompanion.models.base  ClassificationModel fitted in 0.96s on 32551 rows x 10 cols

2026-09-13 11:21:47  INFO      dscompanion.tuning.backends.optuna_backend  Trial 14 params={'n_estimators': 888, 'max_depth': 7, 'learning_rate': 0.02892070398572207, 'subsample': 0.8742018432515738, 'colsample_bytree': 0.8649174147658507, 'reg_alpha': 0.06128695315404711, 'reg_lambda': 0.0038047449717054467, 'min_child_weight': 6} score=0.917529

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:47] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:48  INFO      dscompanion.models.base  ClassificationModel fitted in 0.50s on 32551 rows x 10 cols

2026-09-13 11:21:48  INFO      dscompanion.tuning.backends.optuna_backend  Trial 15 params={'n_estimators': 999, 'max_depth': 7, 'learning_rate': 0.06689802001564377, 'subsample': 0.6662225125541512, 'colsample_bytree': 0.7304453570550351, 'reg_alpha': 0.21042137543560924, 'reg_lambda': 0.026007863858629077, 'min_child_weight': 5} score=0.918898

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:48] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:48  INFO      dscompanion.models.base  ClassificationModel fitted in 0.58s on 32551 rows x 10 cols

2026-09-13 11:21:48  INFO      dscompanion.tuning.backends.optuna_backend  Trial 16 params={'n_estimators': 944, 'max_depth': 7, 'learning_rate': 0.059868929643323465, 'subsample': 0.631674124625631, 'colsample_bytree': 0.6903079053662714, 'reg_alpha': 0.19435277516526905, 'reg_lambda': 0.05876939689970721, 'min_child_weight': 12} score=0.915544

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:48] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:49  INFO      dscompanion.models.base  ClassificationModel fitted in 0.58s on 32551 rows x 10 cols

2026-09-13 11:21:49  INFO      dscompanion.tuning.backends.optuna_backend  Trial 17 params={'n_estimators': 991, 'max_depth': 5, 'learning_rate': 0.06491770277453239, 'subsample': 0.670527857554569, 'colsample_bytree': 0.7322122963145701, 'reg_alpha': 0.5873677639273371, 'reg_lambda': 0.0005119858741508421, 'min_child_weight': 6} score=0.915853

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:49] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:51  INFO      dscompanion.models.base  ClassificationModel fitted in 1.87s on 32551 rows x 10 cols

2026-09-13 11:21:51  INFO      dscompanion.tuning.backends.optuna_backend  Trial 18 params={'n_estimators': 801, 'max_depth': 9, 'learning_rate': 0.02369822420460336, 'subsample': 0.7701341999461423, 'colsample_bytree': 0.7508280521664681, 'reg_alpha': 0.033159340386299745, 'reg_lambda': 0.29709747587057184, 'min_child_weight': 14} score=0.918617

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:51] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:52  INFO      dscompanion.models.base  ClassificationModel fitted in 0.90s on 32551 rows x 10 cols

2026-09-13 11:21:52  INFO      dscompanion.tuning.backends.optuna_backend  Trial 19 params={'n_estimators': 719, 'max_depth': 7, 'learning_rate': 0.04744071693453088, 'subsample': 0.6782187820269976, 'colsample_bytree': 0.8220566304159806, 'reg_alpha': 0.005009895931189415, 'reg_lambda': 0.018082995685667725, 'min_child_weight': 6} score=0.918398

2026-09-13 11:21:52  INFO      dscompanion.tuning.backends.optuna_backend  Optuna finished — best roc_auc=0.9192 in 20 trials

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:52] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:53  INFO      dscompanion.models.base  ClassificationModel fitted in 1.19s on 32551 rows x 10 cols

2026-09-13 11:21:53  INFO      dscompanion.pipeline.runner  [10/13] Evaluating

2026-09-13 11:21:53  INFO      dscompanion.pipeline.runner  [11/13] Calibration

2026-09-13 11:21:53  INFO      dscompanion.calibration.calibrator  Calibrator fitted — method=isotonic, ECE: 0.0166 → 0.0002

2026-09-13 11:21:53  INFO      dscompanion.models.base  Model saved to reports/20260913_112133/model/bank_marketing_tuned_v1.0_model.joblib

2026-09-13 11:21:53  INFO      dscompanion.pipeline.runner  [12/13] SHAP skipped (explain.shap_enabled=False)

2026-09-13 11:21:53  INFO      dscompanion.pipeline.runner  [12/13] Permutation importance skipped (explain.permutation_enabled=False)

2026-09-13 11:21:53  INFO      dscompanion.pipeline.runner  [13/13] Generating report + logging run

2026-09-13 11:21:53  INFO      dscompanion.docs.model_card  ModelCard generated — 14 sections

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  Run started — 20260913 (bank_marketing_tuned_v1.0) tags={'owner': '', 'algorithm': 'xgboost', 'task': 'classification'}

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  artifact reports/20260913_112133/config.yaml -> config

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric train_f1=0.66801 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric train_precision=0.815053 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric train_recall=0.565914 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric train_roc_auc=0.959498 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric train_gini=0.918997 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric train_ks_statistic=0.785403 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric train_log_loss=0.167501 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric test_f1=0.494672 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric test_precision=0.608276 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric test_recall=0.416824 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric test_roc_auc=0.917092 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric test_gini=0.834184 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric test_ks_statistic=0.70405 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric test_log_loss=0.217478 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric test_psi=0.0013 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric val_f1=0.501401 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric val_precision=0.61512 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric val_recall=0.423168 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric val_roc_auc=0.919164 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric val_gini=0.838329 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric val_ks_statistic=0.70797 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric val_log_loss=0.214757 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric val_psi=0.000925 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric features_before_selection=16 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  metric features_after_selection=10 step=None

2026-09-13 11:21:53  INFO      dscompanion.tracking.run_context  params {'objective': 'binary:logistic', 'base_score': 'None', 'booster': 'None', 'callbacks': 'None', 'colsample_bylevel': 'None', 'colsample_bynode': 'None', 'colsample_bytree': '0.856148643942211', 'device': 'None', 'early_stopping_rounds': '20', 'enable_categorical': 'False', 'eval_metric': 'auc', 'feature_types': 'None', 'feature_weights': 'None', 'gamma': 'None', 'grow_policy': 'None', 'importance_type': 'None', 'interaction_constraints': 'None', 'learning_rate': '0.024795803650758556', 'max_bin': 'None', 'max_cat_threshold': 'None', 'max_cat_to_onehot': 'None', 'max_delta_step': 'None', 'max_depth': '8', 'max_leaves': 'None', 'min_child_weight': '5', 'missing': 'nan', 'monotone_constraints': 'None', 'multi_strategy': 'None', 'n_estimators': '721', 'n_jobs': '-1', 'num_parallel_tree': 'None', 'random_state': '42', 'reg_alpha': '0.005351416165734628', 'reg_lambda': '0.022055966549515183', 'sampling_method': 'None', 'scale_pos_weight': '1', 'subsample': '0.7650970966716663', 'tree_method': 'None', 'validate_parameters': 'None', 'verbosity': 'None', 'class_weight': '{0: 0.5662422154959469, 1: 4.274028361344538}'}

2026-09-13 11:21:53  INFO      dscompanion.pipeline.runner  config_deviations: tuning.enabled=True (default False) | tuning.n_trials=20 (default 50)

2026-09-13 11:21:53  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:53  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:53  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:53  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:55  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:55  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:55  INFO      dscompanion.docs.model_card  ModelCard (xlsx) → reports/20260913_112133/reports/bank_marketing_tuned_v1.0_model_card.xlsx

2026-09-13 11:21:55  INFO      dscompanion.tracking.run_context  artifact reports/20260913_112133/reports/bank_marketing_tuned_v1.0_model_card.xlsx -> excel_report

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  Excel model card written → reports/20260913_112133/reports/bank_marketing_tuned_v1.0_model_card.xlsx

2026-09-13 11:21:55  INFO      dscompanion.tracking.run_context  Run finished — 20260913

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  Pipeline complete — 22.3s  |  Run: 20260913_112133

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  Report: n/a

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  ============================================================

Best params found:
{'n_estimators': 721, 'max_depth': 8, 'learning_rate': 0.024795803650758556, 'subsample': 0.7650970966716663, 'colsample_bytree': 0.856148643942211, 'reg_alpha': 0.005351416165734628, 'reg_lambda': 0.022055966549515183, 'min_child_weight': 5}

split             test     train       val
metric
f1            0.494672  0.668010  0.501401
gini          0.834184  0.918997  0.838329
ks_statistic  0.704050  0.785403  0.707970
log_loss      0.217478  0.167501  0.214757
precision     0.608276  0.815053  0.615120
psi           0.001300       NaN  0.000925
recall        0.416824  0.565914  0.423168
roc_auc       0.917092  0.959498  0.919164

## Explainability: SHAP vs. permutation importance

dscompanion supports two explainability approaches with different cost/speed tradeoffs:

- **`permutation_enabled`** (cheap, model-agnostic): shuffles each feature and measures
  the drop in performance. Fast, works for any estimator. This is the sensible default.
- **`shap_enabled`** (more expensive, more detailed): computes per-prediction feature
  attributions via SHAP values. Off by default — it's opt-in because it's genuinely
  more expensive to compute, not because anything is wrong with it.

We'll use permutation importance here since it's the lighter-weight default; SHAP is
available the same way if you want the extra detail (just flip `shap_enabled=True`).

In [8]:
cfg_explain = PipelineConfig(
    name="bank_marketing_explain",
    data={"path": str(data_path), "format": "parquet", "target": "y"},
    split={"method": "stratified", "test_size": 0.2, "val_size": 0.1},
    model={"task": "classification", "algorithm": "xgboost"},
    explain={"permutation_enabled": True},
    reporting={"output_dir": "reports", "html_report": False},
)
result_explain = PipelineRunner(cfg_explain).run()

display(result_explain.permutation_importance.importance_table())
fig = result_explain.permutation_importance.summary_plot()
fig.show()

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  PipelineRunner  |  bank_marketing_explain  v1.0

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  Owner: unset  |  Task: classification  |  Algorithm: xgboost

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:21:55  WARNING   dscompanion.pipeline.runner  Non-default config choices (will appear in report):

2026-09-13 11:21:55  WARNING   dscompanion.pipeline.runner    ⚠  explain.permutation_enabled = True  (default: False)

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  Run directory: reports/20260913_112155

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  [1/13] Loading data

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner         Loaded 45211 rows × 17 columns

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  [2/13] Splitting data

2026-09-13 11:21:55  INFO      dscompanion.split.splitter  Splitting 45,211 rows  strategy='stratified'

2026-09-13 11:21:55  INFO      dscompanion.split.splitter
DataSplit — strategy='stratified'  target='y'
  n_features : 16
  train   :  32,551 rows  event_rate=0.117
  val     :   3,617 rows  event_rate=0.117
  test    :   9,043 rows  event_rate=0.117
  oot     :       0 rows  event_rate=0.000

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  [3/13] EDA

2026-09-13 11:21:55  INFO      dscompanion.eda.report  EDAReport.run_all — starting univariate

2026-09-13 11:21:55  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:55  INFO      dscompanion.eda.report  EDAReport.run_all — bivariate

2026-09-13 11:21:55  INFO      dscompanion.eda.bivariate  BivariateAnalyser.fit — 32551 rows, 16 features

2026-09-13 11:21:55  INFO      dscompanion.eda.report  EDAReport.run_all — multivariate

2026-09-13 11:21:55  INFO      dscompanion.eda.multivariate  MultivariateAnalyser.fit — 32551 rows, 7 numeric columns

2026-09-13 11:21:55  INFO      dscompanion.eda.report  EDAReport.run_all — missingness

2026-09-13 11:21:55  INFO      dscompanion.eda.missingness  MissingnessAnalyser fitted — 500 rows, 16 columns, 4 with partial missingness

2026-09-13 11:21:55  INFO      dscompanion.eda.report  EDAReport.run_all — complete

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner         EDA complete

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  [4/13] Target treatment

2026-09-13 11:21:55  INFO      dscompanion.pipeline.runner  [5/13] Feature processing (impute → encode → scale)

2026-09-13 11:21:55  INFO      dscompanion.features.imputer  SmartImputer fitted — 4 cols imputed, 0 indicators

2026-09-13 11:21:55  WARNING   dscompanion.features.leakage_guard  WARNING — 'day_of_week' name contains target string

2026-09-13 11:21:55  WARNING   dscompanion.features.leakage_guard  WARNING — 'pdays' name contains target string

2026-09-13 11:21:55  INFO      dscompanion.features.pipeline  Leakage check — 0 critical, 2 warnings

2026-09-13 11:21:56  INFO      dscompanion.features.encoder  OrdinalEncoder fitted — cols=9

2026-09-13 11:21:56  INFO      dscompanion.features.scaler  SmartScaler fitted — strategy=none, 16 numeric cols

2026-09-13 11:21:56  INFO      dscompanion.features.pipeline  FeatureProcessingPipeline fitted — 16 output features

2026-09-13 11:21:56  INFO      dscompanion.pipeline.runner  [6/13] Feature selection

2026-09-13 11:21:56  INFO      dscompanion.selection.feature_selectors  NullRateSelector: removed 0 / 16 features

2026-09-13 11:21:56  INFO      dscompanion.selection.selection_pipeline  NullRateSelector: 16 → 16 features

2026-09-13 11:21:56  INFO      dscompanion.selection.feature_selectors  ConstantSelector: removed 0 / 16 features

2026-09-13 11:21:56  INFO      dscompanion.selection.selection_pipeline  ConstantSelector: 16 → 16 features

2026-09-13 11:21:56  INFO      dscompanion.selection.feature_selectors  CardinalitySelector: removed 0 / 16 features

2026-09-13 11:21:56  INFO      dscompanion.selection.selection_pipeline  CardinalitySelector: 16 → 16 features

2026-09-13 11:21:56  INFO      dscompanion.selection.feature_selectors  CorrelationSelector: removed 0 / 16 features

2026-09-13 11:21:56  INFO      dscompanion.selection.selection_pipeline  CorrelationSelector: 16 → 16 features

2026-09-13 11:21:56  INFO      dscompanion.selection.feature_selectors  IVSelector: removed 6 / 16 features (threshold=0.0200)

2026-09-13 11:21:56  INFO      dscompanion.selection.selection_pipeline  IVSelector: 16 → 10 features

2026-09-13 11:21:56  INFO      dscompanion.selection.selection_pipeline  FeatureSelectionPipeline: 16 → 10 features retained

2026-09-13 11:21:56  INFO      dscompanion.pipeline.runner         Features: 16 → 10 (removed 6)

2026-09-13 11:21:56  INFO      dscompanion.pipeline.runner  [7/13] Imbalance handling

2026-09-13 11:21:56  INFO      dscompanion.pipeline.runner  [8/13] Training xgboost

/Users/dsnaveen/miniconda3/envs/mlcore312/lib/python3.12/site-packages/xgboost/callback.py:386: UserWarning: [11:21:56] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "class_weight" } are not used.

  self.starting_round = model.num_boosted_rounds()

2026-09-13 11:21:56  INFO      dscompanion.models.base  ClassificationModel fitted in 0.80s on 32551 rows x 10 cols

2026-09-13 11:21:56  INFO      dscompanion.pipeline.runner  [9/13] Tuning skipped (tuning.enabled=False)

2026-09-13 11:21:56  INFO      dscompanion.pipeline.runner  [10/13] Evaluating

2026-09-13 11:21:57  INFO      dscompanion.pipeline.runner  [11/13] Calibration

2026-09-13 11:21:57  INFO      dscompanion.calibration.calibrator  Calibrator fitted — method=isotonic, ECE: 0.0120 → 0.0001

2026-09-13 11:21:57  INFO      dscompanion.models.base  Model saved to reports/20260913_112155/model/bank_marketing_explain_v1.0_model.joblib

2026-09-13 11:21:57  INFO      dscompanion.pipeline.runner  [12/13] SHAP skipped (explain.shap_enabled=False)

2026-09-13 11:21:57  INFO      dscompanion.pipeline.runner  [12/13] Permutation importance (n_repeats=10, sample=5000)

2026-09-13 11:21:57  INFO      dscompanion.explain.permutation_importance  PermutationImportanceAnalyser.fit — 5000 rows, 10 features, scoring=roc_auc, n_repeats=10

2026-09-13 11:21:57  INFO      dscompanion.pipeline.runner  [13/13] Generating report + logging run

2026-09-13 11:21:57  INFO      dscompanion.docs.model_card  ModelCard generated — 14 sections

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  Run started — 20260913 (bank_marketing_explain_v1.0) tags={'owner': '', 'algorithm': 'xgboost', 'task': 'classification'}

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  artifact reports/20260913_112155/config.yaml -> config

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric train_f1=0.619107 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric train_precision=0.756061 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric train_recall=0.52416 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric train_roc_auc=0.950745 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric train_gini=0.901489 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric train_ks_statistic=0.76616 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric train_log_loss=0.178049 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric test_f1=0.501399 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric test_precision=0.61454 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric test_recall=0.42344 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric test_roc_auc=0.916387 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric test_gini=0.832773 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric test_ks_statistic=0.7046 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric test_log_loss=0.218092 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric test_psi=0.001125 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric val_f1=0.498592 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric val_precision=0.616725 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric val_recall=0.41844 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric val_roc_auc=0.917421 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric val_gini=0.834841 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric val_ks_statistic=0.699113 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric val_log_loss=0.215935 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric val_psi=0.001947 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric features_before_selection=16 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  metric features_after_selection=10 step=None

2026-09-13 11:21:57  INFO      dscompanion.tracking.run_context  params {'objective': 'binary:logistic', 'base_score': 'None', 'booster': 'None', 'callbacks': 'None', 'colsample_bylevel': 'None', 'colsample_bynode': 'None', 'colsample_bytree': '0.8', 'device': 'None', 'early_stopping_rounds': '20', 'enable_categorical': 'False', 'eval_metric': 'auc', 'feature_types': 'None', 'feature_weights': 'None', 'gamma': 'None', 'grow_policy': 'None', 'importance_type': 'None', 'interaction_constraints': 'None', 'learning_rate': '0.05', 'max_bin': 'None', 'max_cat_threshold': 'None', 'max_cat_to_onehot': 'None', 'max_delta_step': 'None', 'max_depth': '6', 'max_leaves': 'None', 'min_child_weight': '5', 'missing': 'nan', 'monotone_constraints': 'None', 'multi_strategy': 'None', 'n_estimators': '300', 'n_jobs': '-1', 'num_parallel_tree': 'None', 'random_state': '42', 'reg_alpha': '0.1', 'reg_lambda': '1.0', 'sampling_method': 'None', 'scale_pos_weight': '1', 'subsample': '0.8', 'tree_method': 'None', 'validate_parameters': 'None', 'verbosity': 'None', 'class_weight': '{0: 0.5662422154959469, 1: 4.274028361344538}'}

2026-09-13 11:21:57  INFO      dscompanion.pipeline.runner  config_deviations: explain.permutation_enabled=True (default False)

2026-09-13 11:21:57  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:57  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:57  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:57  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:58  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:58  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:59  INFO      dscompanion.docs.model_card  ModelCard (xlsx) → reports/20260913_112155/reports/bank_marketing_explain_v1.0_model_card.xlsx

2026-09-13 11:21:59  INFO      dscompanion.tracking.run_context  artifact reports/20260913_112155/reports/bank_marketing_explain_v1.0_model_card.xlsx -> excel_report

2026-09-13 11:21:59  INFO      dscompanion.pipeline.runner  Excel model card written → reports/20260913_112155/reports/bank_marketing_explain_v1.0_model_card.xlsx

2026-09-13 11:21:59  INFO      dscompanion.tracking.run_context  Run finished — 20260913

2026-09-13 11:21:59  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:21:59  INFO      dscompanion.pipeline.runner  Pipeline complete — 3.6s  |  Run: 20260913_112155

2026-09-13 11:21:59  INFO      dscompanion.pipeline.runner  Report: n/a

2026-09-13 11:21:59  INFO      dscompanion.pipeline.runner  ============================================================

       feature  importance_mean  importance_std  rank
0     duration         0.243881        0.010439     1
1        month         0.071695        0.004838     2
2  day_of_week         0.027405        0.001799     3
3     previous         0.026014        0.002249     4
4          age         0.006459        0.000791     5
5      balance         0.003847        0.001014     6
6     campaign         0.003788        0.000854     7
7    education         0.001947        0.000565     8
8      marital         0.001690        0.000472     9
9          job         0.000745        0.000438    10

## Governance-ready model card

`result.model_card` is generated as part of every run. Exporting it produces a
self-contained report — dataset summary, EDA highlights, model configuration,
evaluation metrics, and explainability outputs — meant to be handed to a reviewer,
auditor, or teammate who wasn't in this notebook.

In [9]:
from pathlib import Path

Path("reports").mkdir(exist_ok=True)
result_explain.model_card.to_excel("reports/bank_marketing_model_card.xlsx")
result_explain.model_card.to_html("reports/bank_marketing_model_card.html")
print("Model card written to reports/")

2026-09-13 11:21:59  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:59  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:59  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:21:59  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:22:00  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:22:00  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 7 numeric, 9 categorical, 0 datetime, 0 boolean

2026-09-13 11:22:01  INFO      dscompanion.docs.model_card  ModelCard (xlsx) → reports/bank_marketing_model_card.xlsx

2026-09-13 11:22:01  INFO      dscompanion.docs.model_card  ModelCard (html) → reports/bank_marketing_model_card.html

Model card written to reports/

## Next

[`03_regression_wine_quality.ipynb`](03_regression_wine_quality.ipynb) covers the same
ground for a regression task — and one thing that's classification-only (the
leaderboard) that regression can't use yet.