# Regression Walkthrough: Wine Quality

Same overall shape as [`02_classification_bank_marketing.ipynb`](02_classification_bank_marketing.ipynb),
applied to a regression task, using the UCI **Wine Quality** dataset — 6,497 physicochemical
measurements (acidity, sugar, sulfur dioxide, alcohol, etc.) on Portuguese "Vinho Verde" wine
samples, with `quality` (a 0-10 sensory score) as the target.

This notebook assumes you've read `02` already — it focuses on what's *different* for
regression rather than re-explaining everything from scratch. See [`README.md`](README.md)
for the full notebook index.

In [1]:
!pip install -q dscompanion[notebooks]

zsh:1: no matches found: dscompanion[notebooks]

In [2]:
from pathlib import Path
import pandas as pd
from ucimlrepo import fetch_ucirepo

cache_dir = Path(".data_cache")
cache_dir.mkdir(exist_ok=True)
data_path = cache_dir / "wine_quality.parquet"

if not data_path.exists():
    ds = fetch_ucirepo(id=186)
    df = ds.data.features.copy()
    df["quality"] = ds.data.targets["quality"]
    df.to_parquet(data_path, index=False)
else:
    df = pd.read_parquet(data_path)

print(f"{df.shape[0]} rows, {df.shape[1]} columns")
df["quality"].describe()

6497 rows, 12 columns

count    6497.000000
mean        5.818378
std         0.873255
min         3.000000
25%         5.000000
50%         6.000000
75%         6.000000
max         9.000000
Name: quality, dtype: float64

## Config and run

`quality` is a continuous score, not a class label, so `model.task="regression"`.
`split.method="random"` is used here rather than `"stratified"` — stratified splitting
is a classification concept (it preserves class proportions), which doesn't apply to a
continuous target.

In [3]:
from dscompanion.pipeline import PipelineConfig, PipelineRunner

cfg = PipelineConfig(
    name="wine_quality_regression",
    data={"path": str(data_path), "format": "parquet", "target": "quality"},
    split={"method": "random", "test_size": 0.2, "val_size": 0.1},
    model={"task": "regression", "algorithm": "xgboost"},
    reporting={"output_dir": "reports", "html_report": True},
)
result = PipelineRunner(cfg).run()
result.metrics.pivot(index="metric", columns="split", values="value")

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  PipelineRunner  |  wine_quality_regression  v1.0

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  Owner: unset  |  Task: regression  |  Algorithm: xgboost

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:20:05  WARNING   dscompanion.pipeline.runner  Pre-flight: target.imbalance.strategy='class_weight' is only applicable to classification tasks. It will be ignored.

2026-09-13 11:20:05  WARNING   dscompanion.pipeline.runner  Non-default config choices (will appear in report):

2026-09-13 11:20:05  WARNING   dscompanion.pipeline.runner    ⚠  reporting.html_report = True  (default: False)

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  Run directory: reports/20260913_112005

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  [1/13] Loading data

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner         Loaded 6497 rows × 12 columns

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  [2/13] Splitting data

2026-09-13 11:20:05  INFO      dscompanion.split.splitter  Splitting 6,497 rows  strategy='random'

2026-09-13 11:20:05  INFO      dscompanion.split.splitter
DataSplit — strategy='random'  target='quality'
  n_features : 11
  train   :   4,679 rows  event_rate=5.819
  val     :     519 rows  event_rate=5.780
  test    :   1,299 rows  event_rate=5.833
  oot     :       0 rows  event_rate=0.000

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  [3/13] EDA

2026-09-13 11:20:05  INFO      dscompanion.eda.report  EDAReport.run_all — starting univariate

2026-09-13 11:20:05  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 11 numeric, 0 categorical, 0 datetime, 0 boolean

2026-09-13 11:20:05  INFO      dscompanion.eda.report  EDAReport.run_all — bivariate

2026-09-13 11:20:05  INFO      dscompanion.eda.bivariate  BivariateAnalyser.fit — 4679 rows, 11 features

2026-09-13 11:20:05  INFO      dscompanion.eda.report  EDAReport.run_all — multivariate

2026-09-13 11:20:05  INFO      dscompanion.eda.multivariate  MultivariateAnalyser.fit — 4679 rows, 11 numeric columns

2026-09-13 11:20:05  INFO      dscompanion.eda.report  EDAReport.run_all — missingness

2026-09-13 11:20:05  INFO      dscompanion.eda.missingness  MissingnessAnalyser fitted — 500 rows, 11 columns, 0 with partial missingness

2026-09-13 11:20:05  INFO      dscompanion.eda.report  EDAReport.run_all — complete

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner         EDA complete

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  [4/13] Target treatment

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  [5/13] Feature processing (impute → encode → scale)

2026-09-13 11:20:05  INFO      dscompanion.features.imputer  SmartImputer fitted — 0 cols imputed, 0 indicators

2026-09-13 11:20:05  INFO      dscompanion.features.pipeline  Leakage check — 0 critical, 0 warnings

2026-09-13 11:20:05  INFO      dscompanion.features.scaler  SmartScaler fitted — strategy=none, 11 numeric cols

2026-09-13 11:20:05  INFO      dscompanion.features.pipeline  FeatureProcessingPipeline fitted — 11 output features

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  [6/13] Feature selection

2026-09-13 11:20:05  INFO      dscompanion.selection.feature_selectors  NullRateSelector: removed 0 / 11 features

2026-09-13 11:20:05  INFO      dscompanion.selection.selection_pipeline  NullRateSelector: 11 → 11 features

2026-09-13 11:20:05  INFO      dscompanion.selection.feature_selectors  ConstantSelector: removed 0 / 11 features

2026-09-13 11:20:05  INFO      dscompanion.selection.selection_pipeline  ConstantSelector: 11 → 11 features

2026-09-13 11:20:05  INFO      dscompanion.selection.feature_selectors  CardinalitySelector: removed 0 / 11 features

2026-09-13 11:20:05  INFO      dscompanion.selection.selection_pipeline  CardinalitySelector: 11 → 11 features

2026-09-13 11:20:05  INFO      dscompanion.selection.feature_selectors  CorrelationSelector: removed 0 / 11 features

2026-09-13 11:20:05  INFO      dscompanion.selection.selection_pipeline  CorrelationSelector: 11 → 11 features

2026-09-13 11:20:05  INFO      dscompanion.selection.selection_pipeline  FeatureSelectionPipeline: 11 → 11 features retained

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner         Features: 11 → 11 (removed 0)

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  [7/13] Imbalance handling

2026-09-13 11:20:05  INFO      dscompanion.pipeline.runner  [8/13] Training xgboost

2026-09-13 11:20:06  INFO      dscompanion.models.base  RegressionModel fitted in 0.85s on 4679 rows x 11 cols

2026-09-13 11:20:06  INFO      dscompanion.pipeline.runner  [9/13] Tuning skipped (tuning.enabled=False)

2026-09-13 11:20:06  INFO      dscompanion.pipeline.runner  [10/13] Evaluating

2026-09-13 11:20:06  INFO      dscompanion.pipeline.runner  [11/13] Calibration

2026-09-13 11:20:06  INFO      dscompanion.models.base  Model saved to reports/20260913_112005/model/wine_quality_regression_v1.0_model.joblib

2026-09-13 11:20:06  INFO      dscompanion.pipeline.runner  [12/13] SHAP skipped (explain.shap_enabled=False)

2026-09-13 11:20:06  INFO      dscompanion.pipeline.runner  [12/13] Permutation importance skipped (explain.permutation_enabled=False)

2026-09-13 11:20:06  INFO      dscompanion.pipeline.runner  [13/13] Generating report + logging run

2026-09-13 11:20:06  INFO      dscompanion.docs.model_card  ModelCard generated — 14 sections

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  Run started — 20260913 (wine_quality_regression_v1.0) tags={'owner': '', 'algorithm': 'xgboost', 'task': 'regression'}

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  artifact reports/20260913_112005/config.yaml -> config

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric train_rmse=0.467092 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric train_mae=0.357836 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric train_r2=0.717293 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric train_mape=0.063154 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric train_median_absolute_error=0.281073 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric test_rmse=0.6371 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric test_mae=0.491205 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric test_r2=0.450055 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric test_mape=0.087427 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric test_median_absolute_error=0.402094 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric val_rmse=0.621751 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric val_mae=0.481416 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric val_r2=0.476101 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric val_mape=0.087725 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric val_median_absolute_error=0.413567 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric features_before_selection=11 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  metric features_after_selection=11 step=None

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  params {'objective': 'reg:squarederror', 'base_score': 'None', 'booster': 'None', 'callbacks': 'None', 'colsample_bylevel': 'None', 'colsample_bynode': 'None', 'colsample_bytree': '0.8', 'device': 'None', 'early_stopping_rounds': 'None', 'enable_categorical': 'False', 'eval_metric': 'None', 'feature_types': 'None', 'feature_weights': 'None', 'gamma': 'None', 'grow_policy': 'None', 'importance_type': 'None', 'interaction_constraints': 'None', 'learning_rate': '0.05', 'max_bin': 'None', 'max_cat_threshold': 'None', 'max_cat_to_onehot': 'None', 'max_delta_step': 'None', 'max_depth': '5', 'max_leaves': 'None', 'min_child_weight': 'None', 'missing': 'nan', 'monotone_constraints': 'None', 'multi_strategy': 'None', 'n_estimators': '300', 'n_jobs': '-1', 'num_parallel_tree': 'None', 'random_state': '42', 'reg_alpha': 'None', 'reg_lambda': 'None', 'sampling_method': 'None', 'scale_pos_weight': 'None', 'subsample': '0.8', 'tree_method': 'None', 'validate_parameters': 'None', 'verbosity': 'None'}

2026-09-13 11:20:06  INFO      dscompanion.pipeline.runner  config_deviations: reporting.html_report=True (default False)

2026-09-13 11:20:06  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 11 numeric, 0 categorical, 0 datetime, 0 boolean

2026-09-13 11:20:06  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 11 numeric, 0 categorical, 0 datetime, 0 boolean

2026-09-13 11:20:06  INFO      dscompanion.docs.model_card  ModelCard (xlsx) → reports/20260913_112005/reports/wine_quality_regression_v1.0_model_card.xlsx

2026-09-13 11:20:06  INFO      dscompanion.tracking.run_context  artifact reports/20260913_112005/reports/wine_quality_regression_v1.0_model_card.xlsx -> excel_report

2026-09-13 11:20:06  INFO      dscompanion.pipeline.runner  Excel model card written → reports/20260913_112005/reports/wine_quality_regression_v1.0_model_card.xlsx

2026-09-13 11:20:06  INFO      dscompanion.docs.html_widgets  Fetching Bootstrap 5 for self-contained model card report

2026-09-13 11:20:07  INFO      dscompanion.docs.html_widgets  Bootstrap assets: embedded

/Users/dsnaveen/projects/domain-ml/src/dscompanion/docs/html_eda.py:535: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([numeric_df, categorical_df], ignore_index=True)
2026-09-13 11:20:07  INFO      dscompanion.docs.model_card  ModelCard (html) → reports/20260913_112005/reports/wine_quality_regression_v1.0_model_card.html

2026-09-13 11:20:07  INFO      dscompanion.tracking.run_context  artifact reports/20260913_112005/reports/wine_quality_regression_v1.0_model_card.html -> report

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  HTML report written → reports/20260913_112005/reports/wine_quality_regression_v1.0_model_card.html

2026-09-13 11:20:07  INFO      dscompanion.tracking.run_context  Run finished — 20260913

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  Pipeline complete — 1.7s  |  Run: 20260913_112005

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  Report: reports/20260913_112005/reports/wine_quality_regression_v1.0_model_card.html

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  ============================================================

split                      test     train       val
metric
mae                    0.491205  0.357836  0.481416
mape                   0.087427  0.063154  0.087725
median_absolute_error  0.402094  0.281073  0.413567
r2                     0.450055  0.717293  0.476101
rmse                   0.637100  0.467092  0.621751

`result.metrics` keeps the same tidy `split`/`metric`/`value` shape used everywhere in
dscompanion — only the metric names change per task. For regression, `metric` takes
exactly five values: `rmse`, `mae`, `r2`, `mape`, and `median_absolute_error`.

## No leaderboard section here

`02` used `LeaderboardConfig(enabled=True)` to compare algorithms automatically. That
feature currently only supports `task="classification"` — `PipelineConfig` itself
rejects `leaderboard.enabled=True` combined with any other task at config-construction
time (a clear validation error, not a confusing crash mid-run). Run the cell below to
see it for yourself:

In [4]:
from pydantic import ValidationError

try:
    PipelineConfig(
        name="this_will_fail",
        data={"path": str(data_path), "format": "parquet", "target": "quality"},
        model={"task": "regression", "algorithm": "xgboost"},
        leaderboard={"enabled": True},
    )
except ValidationError as exc:
    print(exc)

1 validation error for PipelineConfig
  Value error, leaderboard.enabled=True currently requires model.task='classification', got 'regression' [type=value_error, input_value={'name': 'this_will_fail'...ard': {'enabled': True}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/value_error

## Tuning — with a regression-appropriate metric

`TuningConfig`'s defaults (`metric="roc_auc"`, `direction="maximize"`) are shaped for
classification. `roc_auc` doesn't exist in a regression model's evaluation output at
all, so it must be overridden — here, to `rmse`. And unlike `roc_auc` (higher is
better), `rmse` is a loss: lower is better, so `direction="minimize"`.

In [5]:
cfg_tuned = PipelineConfig(
    name="wine_quality_regression_tuned",
    data={"path": str(data_path), "format": "parquet", "target": "quality"},
    split={"method": "random", "test_size": 0.2, "val_size": 0.1},
    model={"task": "regression", "algorithm": "xgboost"},
    tuning={"enabled": True, "n_trials": 20, "metric": "rmse", "direction": "minimize"},
    reporting={"output_dir": "reports", "html_report": False},
)
result_tuned = PipelineRunner(cfg_tuned).run()

print("Best params found:")
print(result_tuned.tuner.best_params_)
result_tuned.metrics.pivot(index="metric", columns="split", values="value")

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  PipelineRunner  |  wine_quality_regression_tuned  v1.0

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  Owner: unset  |  Task: regression  |  Algorithm: xgboost

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:20:07  WARNING   dscompanion.pipeline.runner  Pre-flight: target.imbalance.strategy='class_weight' is only applicable to classification tasks. It will be ignored.

2026-09-13 11:20:07  WARNING   dscompanion.pipeline.runner  Non-default config choices (will appear in report):

2026-09-13 11:20:07  WARNING   dscompanion.pipeline.runner    ⚠  tuning.enabled = True  (default: False)

2026-09-13 11:20:07  WARNING   dscompanion.pipeline.runner    ⚠  tuning.n_trials = 20  (default: 50)

2026-09-13 11:20:07  WARNING   dscompanion.pipeline.runner    ⚠  tuning.metric = rmse  (default: roc_auc)

2026-09-13 11:20:07  WARNING   dscompanion.pipeline.runner    ⚠  tuning.direction = minimize  (default: maximize)

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  Run directory: reports/20260913_112007

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  [1/13] Loading data

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner         Loaded 6497 rows × 12 columns

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  [2/13] Splitting data

2026-09-13 11:20:07  INFO      dscompanion.split.splitter  Splitting 6,497 rows  strategy='random'

2026-09-13 11:20:07  INFO      dscompanion.split.splitter
DataSplit — strategy='random'  target='quality'
  n_features : 11
  train   :   4,679 rows  event_rate=5.819
  val     :     519 rows  event_rate=5.780
  test    :   1,299 rows  event_rate=5.833
  oot     :       0 rows  event_rate=0.000

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  [3/13] EDA

2026-09-13 11:20:07  INFO      dscompanion.eda.report  EDAReport.run_all — starting univariate

2026-09-13 11:20:07  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 11 numeric, 0 categorical, 0 datetime, 0 boolean

2026-09-13 11:20:07  INFO      dscompanion.eda.report  EDAReport.run_all — bivariate

2026-09-13 11:20:07  INFO      dscompanion.eda.bivariate  BivariateAnalyser.fit — 4679 rows, 11 features

2026-09-13 11:20:07  INFO      dscompanion.eda.report  EDAReport.run_all — multivariate

2026-09-13 11:20:07  INFO      dscompanion.eda.multivariate  MultivariateAnalyser.fit — 4679 rows, 11 numeric columns

2026-09-13 11:20:07  INFO      dscompanion.eda.report  EDAReport.run_all — missingness

2026-09-13 11:20:07  INFO      dscompanion.eda.missingness  MissingnessAnalyser fitted — 500 rows, 11 columns, 0 with partial missingness

2026-09-13 11:20:07  INFO      dscompanion.eda.report  EDAReport.run_all — complete

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner         EDA complete

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  [4/13] Target treatment

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  [5/13] Feature processing (impute → encode → scale)

2026-09-13 11:20:07  INFO      dscompanion.features.imputer  SmartImputer fitted — 0 cols imputed, 0 indicators

2026-09-13 11:20:07  INFO      dscompanion.features.pipeline  Leakage check — 0 critical, 0 warnings

2026-09-13 11:20:07  INFO      dscompanion.features.scaler  SmartScaler fitted — strategy=none, 11 numeric cols

2026-09-13 11:20:07  INFO      dscompanion.features.pipeline  FeatureProcessingPipeline fitted — 11 output features

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  [6/13] Feature selection

2026-09-13 11:20:07  INFO      dscompanion.selection.feature_selectors  NullRateSelector: removed 0 / 11 features

2026-09-13 11:20:07  INFO      dscompanion.selection.selection_pipeline  NullRateSelector: 11 → 11 features

2026-09-13 11:20:07  INFO      dscompanion.selection.feature_selectors  ConstantSelector: removed 0 / 11 features

2026-09-13 11:20:07  INFO      dscompanion.selection.selection_pipeline  ConstantSelector: 11 → 11 features

2026-09-13 11:20:07  INFO      dscompanion.selection.feature_selectors  CardinalitySelector: removed 0 / 11 features

2026-09-13 11:20:07  INFO      dscompanion.selection.selection_pipeline  CardinalitySelector: 11 → 11 features

2026-09-13 11:20:07  INFO      dscompanion.selection.feature_selectors  CorrelationSelector: removed 0 / 11 features

2026-09-13 11:20:07  INFO      dscompanion.selection.selection_pipeline  CorrelationSelector: 11 → 11 features

2026-09-13 11:20:07  INFO      dscompanion.selection.selection_pipeline  FeatureSelectionPipeline: 11 → 11 features retained

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner         Features: 11 → 11 (removed 0)

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  [7/13] Imbalance handling

2026-09-13 11:20:07  INFO      dscompanion.pipeline.runner  [8/13] Training xgboost

2026-09-13 11:20:08  INFO      dscompanion.models.base  RegressionModel fitted in 0.89s on 4679 rows x 11 cols

2026-09-13 11:20:08  INFO      dscompanion.pipeline.runner  [9/13] Hyperparameter tuning (20 trials)

2026-09-13 11:20:10  INFO      dscompanion.models.base  RegressionModel fitted in 1.96s on 4679 rows x 11 cols

2026-09-13 11:20:10  INFO      dscompanion.tuning.backends.optuna_backend  Trial 0 params={'n_estimators': 437, 'max_depth': 8, 'learning_rate': 0.1205712628744377, 'subsample': 0.8394633936788146, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 0.000602521573620386, 'reg_lambda': 0.00019517224641449495} score=0.568763

2026-09-13 11:20:13  INFO      dscompanion.models.base  RegressionModel fitted in 2.89s on 4679 rows x 11 cols

2026-09-13 11:20:13  INFO      dscompanion.tuning.backends.optuna_backend  Trial 1 params={'n_estimators': 880, 'max_depth': 6, 'learning_rate': 0.11114989443094977, 'subsample': 0.608233797718321, 'colsample_bytree': 0.9849549260809971, 'reg_alpha': 1.452824663751602, 'reg_lambda': 0.0011526449540315614} score=0.612017

2026-09-13 11:20:13  INFO      dscompanion.models.base  RegressionModel fitted in 0.61s on 4679 rows x 11 cols

2026-09-13 11:20:13  INFO      dscompanion.tuning.backends.optuna_backend  Trial 2 params={'n_estimators': 263, 'max_depth': 4, 'learning_rate': 0.028145092716060652, 'subsample': 0.8099025726528951, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 0.0028585493941961923, 'reg_lambda': 0.11462107403425029} score=0.647783

2026-09-13 11:20:14  INFO      dscompanion.models.base  RegressionModel fitted in 0.53s on 4679 rows x 11 cols

2026-09-13 11:20:14  INFO      dscompanion.tuning.backends.optuna_backend  Trial 3 params={'n_estimators': 225, 'max_depth': 4, 'learning_rate': 0.03476649150592621, 'subsample': 0.7824279936868144, 'colsample_bytree': 0.8925879806965068, 'reg_alpha': 0.0009962513222055117, 'reg_lambda': 0.03725393839578886} score=0.647176

2026-09-13 11:20:15  INFO      dscompanion.models.base  RegressionModel fitted in 1.20s on 4679 rows x 11 cols

2026-09-13 11:20:15  INFO      dscompanion.tuning.backends.optuna_backend  Trial 4 params={'n_estimators': 633, 'max_depth': 3, 'learning_rate': 0.07896186801026692, 'subsample': 0.6682096494749166, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 5.55172168524472, 'reg_lambda': 6.732248920775334} score=0.648874

2026-09-13 11:20:17  INFO      dscompanion.models.base  RegressionModel fitted in 1.94s on 4679 rows x 11 cols

2026-09-13 11:20:17  INFO      dscompanion.tuning.backends.optuna_backend  Trial 5 params={'n_estimators': 828, 'max_depth': 4, 'learning_rate': 0.013940346079873234, 'subsample': 0.8736932106048627, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 0.00040755964400728694, 'reg_lambda': 0.02991469302130215} score=0.643464

2026-09-13 11:20:18  INFO      dscompanion.models.base  RegressionModel fitted in 0.59s on 4679 rows x 11 cols

2026-09-13 11:20:18  INFO      dscompanion.tuning.backends.optuna_backend  Trial 6 params={'n_estimators': 130, 'max_depth': 8, 'learning_rate': 0.024112898115291975, 'subsample': 0.8650089137415928, 'colsample_bytree': 0.6558555380447055, 'reg_alpha': 0.039841905944346875, 'reg_lambda': 0.05414413211338523} score=0.613393

2026-09-13 11:20:19  INFO      dscompanion.models.base  RegressionModel fitted in 1.20s on 4679 rows x 11 cols

2026-09-13 11:20:19  INFO      dscompanion.tuning.backends.optuna_backend  Trial 7 params={'n_estimators': 266, 'max_depth': 8, 'learning_rate': 0.13962563737015762, 'subsample': 0.9757995766256756, 'colsample_bytree': 0.9474136752138245, 'reg_alpha': 0.09761125443110452, 'reg_lambda': 4.067908494359543} score=0.587387

2026-09-13 11:20:19  INFO      dscompanion.models.base  RegressionModel fitted in 0.43s on 4679 rows x 11 cols

2026-09-13 11:20:19  INFO      dscompanion.tuning.backends.optuna_backend  Trial 8 params={'n_estimators': 179, 'max_depth': 4, 'learning_rate': 0.011662890273931383, 'subsample': 0.7301321323053057, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 0.002273762810253686, 'reg_lambda': 1.3921548533046488} score=0.691918

2026-09-13 11:20:20  INFO      dscompanion.models.base  RegressionModel fitted in 1.00s on 4679 rows x 11 cols

2026-09-13 11:20:20  INFO      dscompanion.tuning.backends.optuna_backend  Trial 9 params={'n_estimators': 421, 'max_depth': 4, 'learning_rate': 0.06333268775321839, 'subsample': 0.6563696899899051, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 0.0002359137306347715, 'reg_lambda': 8.59873733921227} score=0.622084

2026-09-13 11:20:22  INFO      dscompanion.models.base  RegressionModel fitted in 2.10s on 4679 rows x 11 cols

2026-09-13 11:20:22  INFO      dscompanion.tuning.backends.optuna_backend  Trial 10 params={'n_estimators': 583, 'max_depth': 7, 'learning_rate': 0.2704729722717779, 'subsample': 0.9729161367647149, 'colsample_bytree': 0.5076838686640521, 'reg_alpha': 0.009777249798608703, 'reg_lambda': 0.0001190477483147248} score=0.648083

2026-09-13 11:20:24  INFO      dscompanion.models.base  RegressionModel fitted in 1.55s on 4679 rows x 11 cols

2026-09-13 11:20:24  INFO      dscompanion.tuning.backends.optuna_backend  Trial 11 params={'n_estimators': 393, 'max_depth': 8, 'learning_rate': 0.22281286854438492, 'subsample': 0.9974969943358359, 'colsample_bytree': 0.8123826179152995, 'reg_alpha': 0.11757305209918842, 'reg_lambda': 0.002411934260657859} score=0.592499

2026-09-13 11:20:25  INFO      dscompanion.models.base  RegressionModel fitted in 1.53s on 4679 rows x 11 cols

2026-09-13 11:20:25  INFO      dscompanion.tuning.backends.optuna_backend  Trial 12 params={'n_estimators': 408, 'max_depth': 7, 'learning_rate': 0.13824480987748167, 'subsample': 0.9133597665940176, 'colsample_bytree': 0.6010807595833223, 'reg_alpha': 0.25763445424786896, 'reg_lambda': 0.5814860261239609} score=0.582314

2026-09-13 11:20:27  INFO      dscompanion.models.base  RegressionModel fitted in 1.54s on 4679 rows x 11 cols

2026-09-13 11:20:27  INFO      dscompanion.tuning.backends.optuna_backend  Trial 13 params={'n_estimators': 475, 'max_depth': 6, 'learning_rate': 0.15234515430133896, 'subsample': 0.9058563700626999, 'colsample_bytree': 0.5962032728335486, 'reg_alpha': 0.6792767878855803, 'reg_lambda': 0.3629852778670363} score=0.603551

2026-09-13 11:20:30  INFO      dscompanion.models.base  RegressionModel fitted in 2.56s on 4679 rows x 11 cols

2026-09-13 11:20:30  INFO      dscompanion.tuning.backends.optuna_backend  Trial 14 params={'n_estimators': 686, 'max_depth': 7, 'learning_rate': 0.09595640156721373, 'subsample': 0.9115532751554248, 'colsample_bytree': 0.602298487430077, 'reg_alpha': 0.4804555890653395, 'reg_lambda': 0.004023157294890257} score=0.578991

2026-09-13 11:20:32  INFO      dscompanion.models.base  RegressionModel fitted in 2.65s on 4679 rows x 11 cols

2026-09-13 11:20:32  INFO      dscompanion.tuning.backends.optuna_backend  Trial 15 params={'n_estimators': 717, 'max_depth': 7, 'learning_rate': 0.04287547341794409, 'subsample': 0.8010440425491622, 'colsample_bytree': 0.5979644942759227, 'reg_alpha': 0.011669990391363183, 'reg_lambda': 0.00012947240078249806} score=0.574432

2026-09-13 11:20:35  INFO      dscompanion.models.base  RegressionModel fitted in 2.89s on 4679 rows x 11 cols

2026-09-13 11:20:35  INFO      dscompanion.tuning.backends.optuna_backend  Trial 16 params={'n_estimators': 765, 'max_depth': 7, 'learning_rate': 0.04657370744630154, 'subsample': 0.778437892188274, 'colsample_bytree': 0.7947992509228796, 'reg_alpha': 0.00010362517714796021, 'reg_lambda': 0.00011348695571232821} score=0.578645

2026-09-13 11:20:38  INFO      dscompanion.models.base  RegressionModel fitted in 2.39s on 4679 rows x 11 cols

2026-09-13 11:20:38  INFO      dscompanion.tuning.backends.optuna_backend  Trial 17 params={'n_estimators': 730, 'max_depth': 6, 'learning_rate': 0.04848754515310095, 'subsample': 0.7249370496058717, 'colsample_bytree': 0.569632098931771, 'reg_alpha': 0.012359512813751665, 'reg_lambda': 0.0005236009711950082} score=0.580753

2026-09-13 11:20:42  INFO      dscompanion.models.base  RegressionModel fitted in 4.30s on 4679 rows x 11 cols

2026-09-13 11:20:42  INFO      dscompanion.tuning.backends.optuna_backend  Trial 18 params={'n_estimators': 974, 'max_depth': 8, 'learning_rate': 0.017850705608912134, 'subsample': 0.8281270640591984, 'colsample_bytree': 0.6548503898583581, 'reg_alpha': 0.0073752301206687805, 'reg_lambda': 0.010022057377434737} score=0.573905

2026-09-13 11:20:46  INFO      dscompanion.models.base  RegressionModel fitted in 4.18s on 4679 rows x 11 cols

2026-09-13 11:20:46  INFO      dscompanion.tuning.backends.optuna_backend  Trial 19 params={'n_estimators': 984, 'max_depth': 8, 'learning_rate': 0.018093100057472708, 'subsample': 0.8368363390305017, 'colsample_bytree': 0.6487738604888553, 'reg_alpha': 0.0013138721876342655, 'reg_lambda': 0.009338766340962309} score=0.570551

2026-09-13 11:20:46  INFO      dscompanion.tuning.backends.optuna_backend  Optuna finished — best rmse=0.5688 in 20 trials

2026-09-13 11:20:48  INFO      dscompanion.models.base  RegressionModel fitted in 1.86s on 4679 rows x 11 cols

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [10/13] Evaluating

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [11/13] Calibration

2026-09-13 11:20:48  INFO      dscompanion.models.base  Model saved to reports/20260913_112007/model/wine_quality_regression_tuned_v1.0_model.joblib

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [12/13] SHAP skipped (explain.shap_enabled=False)

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [12/13] Permutation importance skipped (explain.permutation_enabled=False)

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [13/13] Generating report + logging run

2026-09-13 11:20:48  INFO      dscompanion.docs.model_card  ModelCard generated — 14 sections

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  Run started — 20260913 (wine_quality_regression_tuned_v1.0) tags={'owner': '', 'algorithm': 'xgboost', 'task': 'regression'}

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  artifact reports/20260913_112007/config.yaml -> config

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric train_rmse=0.007328 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric train_mae=0.005285 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric train_r2=0.99993 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric train_mape=0.000929 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric train_median_absolute_error=0.0036 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric test_rmse=0.623205 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric test_mae=0.418853 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric test_r2=0.473782 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric test_mape=0.075279 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric test_median_absolute_error=0.286364 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric val_rmse=0.568763 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric val_mae=0.374364 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric val_r2=0.561593 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric val_mape=0.069096 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric val_median_absolute_error=0.2243 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric features_before_selection=11 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  metric features_after_selection=11 step=None

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  params {'objective': 'reg:squarederror', 'base_score': 'None', 'booster': 'None', 'callbacks': 'None', 'colsample_bylevel': 'None', 'colsample_bynode': 'None', 'colsample_bytree': '0.5780093202212182', 'device': 'None', 'early_stopping_rounds': 'None', 'enable_categorical': 'False', 'eval_metric': 'None', 'feature_types': 'None', 'feature_weights': 'None', 'gamma': 'None', 'grow_policy': 'None', 'importance_type': 'None', 'interaction_constraints': 'None', 'learning_rate': '0.1205712628744377', 'max_bin': 'None', 'max_cat_threshold': 'None', 'max_cat_to_onehot': 'None', 'max_delta_step': 'None', 'max_depth': '8', 'max_leaves': 'None', 'min_child_weight': 'None', 'missing': 'nan', 'monotone_constraints': 'None', 'multi_strategy': 'None', 'n_estimators': '437', 'n_jobs': '-1', 'num_parallel_tree': 'None', 'random_state': '42', 'reg_alpha': '0.000602521573620386', 'reg_lambda': '0.00019517224641449495', 'sampling_method': 'None', 'scale_pos_weight': 'None', 'subsample': '0.8394633936788146', 'tree_method': 'None', 'validate_parameters': 'None', 'verbosity': 'None'}

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  config_deviations: tuning.enabled=True (default False) | tuning.n_trials=20 (default 50) | tuning.metric=rmse (default roc_auc) | tuning.direction=minimize (default maximize)

2026-09-13 11:20:48  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 11 numeric, 0 categorical, 0 datetime, 0 boolean

2026-09-13 11:20:48  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 11 numeric, 0 categorical, 0 datetime, 0 boolean

2026-09-13 11:20:48  INFO      dscompanion.docs.model_card  ModelCard (xlsx) → reports/20260913_112007/reports/wine_quality_regression_tuned_v1.0_model_card.xlsx

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  artifact reports/20260913_112007/reports/wine_quality_regression_tuned_v1.0_model_card.xlsx -> excel_report

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  Excel model card written → reports/20260913_112007/reports/wine_quality_regression_tuned_v1.0_model_card.xlsx

2026-09-13 11:20:48  INFO      dscompanion.tracking.run_context  Run finished — 20260913

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  Pipeline complete — 41.5s  |  Run: 20260913_112007

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  Report: n/a

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  ============================================================

Best params found:
{'n_estimators': 437, 'max_depth': 8, 'learning_rate': 0.1205712628744377, 'subsample': 0.8394633936788146, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 0.000602521573620386, 'reg_lambda': 0.00019517224641449495}

split                      test     train       val
metric
mae                    0.418853  0.005285  0.374364
mape                   0.075279  0.000929  0.069096
median_absolute_error  0.286364  0.003600  0.224300
r2                     0.473782  0.999930  0.561593
rmse                   0.623205  0.007328  0.568763

## Explainability and the model card

Same API as classification — `permutation_enabled`/`shap_enabled` in `ExplainConfig`,
and `result.model_card.to_excel(...)`/`.to_html(...)` for the exported report. Nothing
regression-specific here; it's the same interface across every task.

In [6]:
cfg_explain = PipelineConfig(
    name="wine_quality_explain",
    data={"path": str(data_path), "format": "parquet", "target": "quality"},
    split={"method": "random", "test_size": 0.2, "val_size": 0.1},
    model={"task": "regression", "algorithm": "xgboost"},
    explain={"permutation_enabled": True},
    reporting={"output_dir": "reports", "html_report": False},
)
result_explain = PipelineRunner(cfg_explain).run()

display(result_explain.permutation_importance.importance_table())
fig = result_explain.permutation_importance.summary_plot()
fig.show()

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  PipelineRunner  |  wine_quality_explain  v1.0

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  Owner: unset  |  Task: regression  |  Algorithm: xgboost

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:20:48  WARNING   dscompanion.pipeline.runner  Pre-flight: target.imbalance.strategy='class_weight' is only applicable to classification tasks. It will be ignored.

2026-09-13 11:20:48  WARNING   dscompanion.pipeline.runner  Non-default config choices (will appear in report):

2026-09-13 11:20:48  WARNING   dscompanion.pipeline.runner    ⚠  explain.permutation_enabled = True  (default: False)

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  Run directory: reports/20260913_112048

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [1/13] Loading data

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner         Loaded 6497 rows × 12 columns

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [2/13] Splitting data

2026-09-13 11:20:48  INFO      dscompanion.split.splitter  Splitting 6,497 rows  strategy='random'

2026-09-13 11:20:48  INFO      dscompanion.split.splitter
DataSplit — strategy='random'  target='quality'
  n_features : 11
  train   :   4,679 rows  event_rate=5.819
  val     :     519 rows  event_rate=5.780
  test    :   1,299 rows  event_rate=5.833
  oot     :       0 rows  event_rate=0.000

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [3/13] EDA

2026-09-13 11:20:48  INFO      dscompanion.eda.report  EDAReport.run_all — starting univariate

2026-09-13 11:20:48  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 11 numeric, 0 categorical, 0 datetime, 0 boolean

2026-09-13 11:20:48  INFO      dscompanion.eda.report  EDAReport.run_all — bivariate

2026-09-13 11:20:48  INFO      dscompanion.eda.bivariate  BivariateAnalyser.fit — 4679 rows, 11 features

2026-09-13 11:20:48  INFO      dscompanion.eda.report  EDAReport.run_all — multivariate

2026-09-13 11:20:48  INFO      dscompanion.eda.multivariate  MultivariateAnalyser.fit — 4679 rows, 11 numeric columns

2026-09-13 11:20:48  INFO      dscompanion.eda.report  EDAReport.run_all — missingness

2026-09-13 11:20:48  INFO      dscompanion.eda.missingness  MissingnessAnalyser fitted — 500 rows, 11 columns, 0 with partial missingness

2026-09-13 11:20:48  INFO      dscompanion.eda.report  EDAReport.run_all — complete

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner         EDA complete

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [4/13] Target treatment

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [5/13] Feature processing (impute → encode → scale)

2026-09-13 11:20:48  INFO      dscompanion.features.imputer  SmartImputer fitted — 0 cols imputed, 0 indicators

2026-09-13 11:20:48  INFO      dscompanion.features.pipeline  Leakage check — 0 critical, 0 warnings

2026-09-13 11:20:48  INFO      dscompanion.features.scaler  SmartScaler fitted — strategy=none, 11 numeric cols

2026-09-13 11:20:48  INFO      dscompanion.features.pipeline  FeatureProcessingPipeline fitted — 11 output features

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [6/13] Feature selection

2026-09-13 11:20:48  INFO      dscompanion.selection.feature_selectors  NullRateSelector: removed 0 / 11 features

2026-09-13 11:20:48  INFO      dscompanion.selection.selection_pipeline  NullRateSelector: 11 → 11 features

2026-09-13 11:20:48  INFO      dscompanion.selection.feature_selectors  ConstantSelector: removed 0 / 11 features

2026-09-13 11:20:48  INFO      dscompanion.selection.selection_pipeline  ConstantSelector: 11 → 11 features

2026-09-13 11:20:48  INFO      dscompanion.selection.feature_selectors  CardinalitySelector: removed 0 / 11 features

2026-09-13 11:20:48  INFO      dscompanion.selection.selection_pipeline  CardinalitySelector: 11 → 11 features

2026-09-13 11:20:48  INFO      dscompanion.selection.feature_selectors  CorrelationSelector: removed 0 / 11 features

2026-09-13 11:20:48  INFO      dscompanion.selection.selection_pipeline  CorrelationSelector: 11 → 11 features

2026-09-13 11:20:48  INFO      dscompanion.selection.selection_pipeline  FeatureSelectionPipeline: 11 → 11 features retained

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner         Features: 11 → 11 (removed 0)

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [7/13] Imbalance handling

2026-09-13 11:20:48  INFO      dscompanion.pipeline.runner  [8/13] Training xgboost

2026-09-13 11:20:49  INFO      dscompanion.models.base  RegressionModel fitted in 0.84s on 4679 rows x 11 cols

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  [9/13] Tuning skipped (tuning.enabled=False)

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  [10/13] Evaluating

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  [11/13] Calibration

2026-09-13 11:20:49  INFO      dscompanion.models.base  Model saved to reports/20260913_112048/model/wine_quality_explain_v1.0_model.joblib

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  [12/13] SHAP skipped (explain.shap_enabled=False)

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  [12/13] Permutation importance (n_repeats=10, sample=5000)

2026-09-13 11:20:49  INFO      dscompanion.explain.permutation_importance  PermutationImportanceAnalyser.fit — 1299 rows, 11 features, scoring=r2, n_repeats=10

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  [13/13] Generating report + logging run

2026-09-13 11:20:49  INFO      dscompanion.docs.model_card  ModelCard generated — 14 sections

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  Run started — 20260913 (wine_quality_explain_v1.0) tags={'owner': '', 'algorithm': 'xgboost', 'task': 'regression'}

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  artifact reports/20260913_112048/config.yaml -> config

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric train_rmse=0.467092 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric train_mae=0.357836 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric train_r2=0.717293 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric train_mape=0.063154 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric train_median_absolute_error=0.281073 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric test_rmse=0.6371 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric test_mae=0.491205 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric test_r2=0.450055 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric test_mape=0.087427 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric test_median_absolute_error=0.402094 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric val_rmse=0.621751 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric val_mae=0.481416 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric val_r2=0.476101 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric val_mape=0.087725 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric val_median_absolute_error=0.413567 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric features_before_selection=11 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  metric features_after_selection=11 step=None

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  params {'objective': 'reg:squarederror', 'base_score': 'None', 'booster': 'None', 'callbacks': 'None', 'colsample_bylevel': 'None', 'colsample_bynode': 'None', 'colsample_bytree': '0.8', 'device': 'None', 'early_stopping_rounds': 'None', 'enable_categorical': 'False', 'eval_metric': 'None', 'feature_types': 'None', 'feature_weights': 'None', 'gamma': 'None', 'grow_policy': 'None', 'importance_type': 'None', 'interaction_constraints': 'None', 'learning_rate': '0.05', 'max_bin': 'None', 'max_cat_threshold': 'None', 'max_cat_to_onehot': 'None', 'max_delta_step': 'None', 'max_depth': '5', 'max_leaves': 'None', 'min_child_weight': 'None', 'missing': 'nan', 'monotone_constraints': 'None', 'multi_strategy': 'None', 'n_estimators': '300', 'n_jobs': '-1', 'num_parallel_tree': 'None', 'random_state': '42', 'reg_alpha': 'None', 'reg_lambda': 'None', 'sampling_method': 'None', 'scale_pos_weight': 'None', 'subsample': '0.8', 'tree_method': 'None', 'validate_parameters': 'None', 'verbosity': 'None'}

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  config_deviations: explain.permutation_enabled=True (default False)

2026-09-13 11:20:49  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 11 numeric, 0 categorical, 0 datetime, 0 boolean

2026-09-13 11:20:49  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 11 numeric, 0 categorical, 0 datetime, 0 boolean

2026-09-13 11:20:49  INFO      dscompanion.docs.model_card  ModelCard (xlsx) → reports/20260913_112048/reports/wine_quality_explain_v1.0_model_card.xlsx

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  artifact reports/20260913_112048/reports/wine_quality_explain_v1.0_model_card.xlsx -> excel_report

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  Excel model card written → reports/20260913_112048/reports/wine_quality_explain_v1.0_model_card.xlsx

2026-09-13 11:20:49  INFO      dscompanion.tracking.run_context  Run finished — 20260913

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  ============================================================

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  Pipeline complete — 1.2s  |  Run: 20260913_112048

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  Report: n/a

2026-09-13 11:20:49  INFO      dscompanion.pipeline.runner  ============================================================

                 feature  importance_mean  importance_std  rank
0                alcohol         0.268571        0.010546     1
1    free_sulfur_dioxide         0.136644        0.013185     2
2       volatile_acidity         0.135943        0.007945     3
3              sulphates         0.075187        0.007417     4
4   total_sulfur_dioxide         0.073496        0.004937     5
5         residual_sugar         0.064537        0.007116     6
6                density         0.048726        0.006281     7
7              chlorides         0.037808        0.004914     8
8            citric_acid         0.030304        0.004776     9
9          fixed_acidity         0.025339        0.003535    10
10                    pH         0.024742        0.003785    11

In [7]:
from pathlib import Path

Path("reports").mkdir(exist_ok=True)
result_explain.model_card.to_excel("reports/wine_quality_model_card.xlsx")
result_explain.model_card.to_html("reports/wine_quality_model_card.html")
print("Model card written to reports/")

2026-09-13 11:20:50  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 11 numeric, 0 categorical, 0 datetime, 0 boolean

2026-09-13 11:20:50  INFO      dscompanion.eda.univariate  UnivariateAnalyser fitted — 11 numeric, 0 categorical, 0 datetime, 0 boolean

2026-09-13 11:20:50  INFO      dscompanion.docs.model_card  ModelCard (xlsx) → reports/wine_quality_model_card.xlsx

/Users/dsnaveen/projects/domain-ml/src/dscompanion/docs/html_eda.py:535: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

2026-09-13 11:20:50  INFO      dscompanion.docs.model_card  ModelCard (html) → reports/wine_quality_model_card.html

Model card written to reports/

## Next

[`04_clustering_wholesale_customers.ipynb`](04_clustering_wholesale_customers.ipynb)
covers the last of dscompanion's three tasks: unsupervised clustering, where there's no
label to predict at all — and a config quirk worth understanding as a result.